### ISSUE TITLE
Support completions

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#1]

**Comment by kylebarron** [comment]
Try to make sure that `return list` works the same before and after I get the environment.

**Comment by kylebarron** [comment]
Use pygments to tokenize words? Would be sweet

**Comment by mcaceresb** [comment]
I'm fiddling about with completions; check out [this branch[(https://github.com/mcaceresb/stata_kernel/tree/dev-completions)

This makes a dictionary of variables in memory, locals, and globals after each `do_execute`; it's pretty nice, but there is a noticeable lag (0.1s in my system) to refresh the completions dictionary ):

Are you also working on this? Better ideas?

**Comment by kylebarron** [comment]
When we update the dictionary of variables, locals, and globals, that information doesn't have to complete before we return the results. You could add a `post_do_execute_hook()` function at the end of `StataKernel.do_execute()` [here](https://github.com/mcaceresb/stata_kernel/blob/72b55176cae6c5150edd8a51ceb99a3ebcc6faba/stata_kernel/kernel.py#L111).

**Comment by mcaceresb** [comment]
Brilliant! Very smooth. It's working pretty well now, including scalar and matrix context awareness. Will make a PR and you can see if it gels with what you have in mind for this. Completions are really neat in jupyter.
