### ISSUE TITLE
Add a plain-text version of %browse for use in console

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#101]

**Comment by mcaceresb** [comment]
Can jupyter detect what environment it's being run in? If so this can just be an alias for `list`, right?

**Comment by kylebarron** [comment]
No it can't. You have to respond with multiple mimetypes of the same output. And the frontend chooses the output type that's best to display. So this would run both `list` and get the html, and send both to the frontend.

**Comment by mcaceresb** [comment]
Oh! Didn't realize you could do multiple mime types. Should I put in a fallback for the help magic?

**Comment by kylebarron** [comment]
Yeah that's what I currently do with plots:
https://github.com/kylebarron/stata_kernel/blob/e05c86ee1f5f5e222c55615cf1e95508f6bf64d6/stata_kernel/kernel.py#L119-L130
![image](https://user-images.githubusercontent.com/15164633/44378414-2c1bb900-a4cf-11e8-84b1-fc1b8c8ef2f5.png)

**Comment by mcaceresb** [comment]
Nice.

**Comment by mcaceresb** [comment]
Actually, I think it's probably a better idea to just say 'This front-end cannot display HTML help.'

**Comment by kylebarron** [comment]
Yeah that's valid
