### ISSUE TITLE
close tick mark showing in local

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#102]
In Atom this conflicts with the standard bracket-matcher settings... so when I type the first backtick, it automatically matches it with a forward tick, so it's not ideal for the completions to also add a forward tick.

![image](https://user-images.githubusercontent.com/15164633/44377956-fb3a8480-a4cc-11e8-97e4-818874c4298b.png)

**Comment by kylebarron** [comment]
I.e. becomes
![image](https://user-images.githubusercontent.com/15164633/44378023-5c625800-a4cd-11e8-96dd-3e7dee06d1dc.png)

**Comment by kylebarron** [comment]
@mcaceresb

**Comment by mcaceresb** [comment]
I don't get this issue on the console or notebooks, btw. Will see what I can do for atom.

**Comment by mcaceresb** [comment]
Don't really get this issue on atom either... Is there a setting I need to switch?

**Comment by mcaceresb** [comment]
Ah, atom is not showing me kernel suggestions. How do I turn that on?

**Comment by kylebarron** [comment]
Well if you have my `language-stata` package installed, when you open up a do file, it sets the bracket-matcher to automatically enter a `'`. Do you have that package installed?

**Comment by kylebarron** [comment]
![image](https://user-images.githubusercontent.com/15164633/44378341-e0690f80-a4ce-11e8-98dd-b26810f4a259.png)
![image](https://user-images.githubusercontent.com/15164633/44378344-e4952d00-a4ce-11e8-9717-5d01d1d2e4b6.png)

**Comment by mcaceresb** [comment]
Not trying inside a string. Just not getting any suggestions.

![error_local_completions_atom](https://user-images.githubusercontent.com/4219197/44378769-d2b48980-a4d0-11e8-9776-e42036236db2.png)

**Comment by mcaceresb** [comment]
So, I can't debug because I can't reproduce. So what I could do is just not close the suggestion. Will be a bit of work but not too much (I'd have to turn it off for ${} and `=scalar()` as well).

**Comment by kylebarron** [comment]
Weird. None of those suggestions are coming from Hydrogen/the kernel. They're all coming from language-stata / other text in the editor.

**Comment by kylebarron** [comment]
This is getting annoying for me. To my mind, the autocompletion should be separate from the bracket completion. I'd be surprised if there weren't a plugin for Jupyter qtconsole to do bracket (and quote) completions.

**Comment by mcaceresb** [comment]
Sure; it's not too hard to take out.
