### ISSUE TITLE
Flesh out --help menus for magics

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#106]
![image](https://user-images.githubusercontent.com/15164633/44380593-3c856100-a4da-11e8-912a-07d242ec757f.png)

**Comment by mcaceresb** [comment]
w/my PR I think `%browse` is the only one that doesn't have a help menu. Before it was `%help` as well.

**Comment by kylebarron** [comment]
It might be nice for %help with no arguments to print a basic description of magics available or the kernel

**Comment by mcaceresb** [comment]
How about

```
%help

stata_kernel {version} for Stata {stata_version}. Type

    %help kernel

for help on using the kernel and

    %help magics

for info on magics. To fetch HTML help for a Stata command type

    %help command_or_topic
```

**Comment by mcaceresb** [comment]
Maybe switch about the order but how's the basic gist of that?

**Comment by kylebarron** [comment]
Perfect

**Comment by mcaceresb** [comment]
Ok. Now on to what to say for each of those things. Maybe use pandoc to render or plain text

- docs/src/using_stata_kernel/magics.md for `%help magics`
- docs/src/index.md for `%help kernel`

Or is that overkill?

**Comment by kylebarron** [comment]
That's fine, but use Pandoc locally, don't add it as a dependency.

**Comment by mcaceresb** [comment]
Mmm. Ok; I'll add rendered versions in docs. Will have to remember to re-render whenever these things get updated. I wonder if there is a way to automate that.

**Comment by kylebarron** [comment]
Yeah def a way to automate that. I can try to look into that. However I'm leaving for a week of vacation Friday night and won't really have much time the next few days to work on this.
