### ISSUE TITLE
first letter missing from every command in initialization

### ISSUE THREAD

**Issue by bermudaparty** [kylebarron/stata_kernel#127]
#### Code Sample

```stata
set obs 10000
  generate u1 = runiform()

```
#### Problem description

I'm using the setup with Atom and Hydrogen, so I hope this is the correct place to report this issue. Apologies if not.

So I created a very simple test.do file with just the above code to see how everything works. The first time i press CTRL+Enter some kind of initialization happens and some commands get executed in stata (`cd ".do File Directory"`; `set more on`; etc.). However, from every command (except the first one) the first letter is missing (`et more on`; `et pagesize 100`; etc).

#### Expected Output
No errors.

#### Debugging log

I didn't find this.

#### Package Version

1.4.1

Windows 10

Stata 13.0, MP-64

(I had to install the package by manually setting the `stata_path` in` install.py`. Don't know if this causes the problem. Seems unlikely.)

#### Received Output
![grafik](https://user-images.githubusercontent.com/17196288/45001653-3e1d5180-afcf-11e8-85d3-0f6bbdc85720.png)

**Comment by kylebarron** [comment]
That's interesting. I'm guessing it's most likely an issue with Stata 13, since I've only tested it with Stata 14 and 15.

I don't think I'll be able to get a copy of Stata 13 for me to test with, so I'll create a Git branch with possible fixes for you to try out. 

With the nature of the output, I'm guessing that it's a Windows end-of-line issue. We currently only use `\n` to delimit multiple lines; while Windows usually uses `\r\n` it hasn't been an issue with Stata 15 on Windows. 

I'm on a plane at the moment with mobile-only access, but tomorrow I'll create a branch for you to try.

**Comment by kylebarron** [comment]
@bermudaparty  Can you try 
```
pip install git+https://github.com/kylebarron/stata_kernel@windows-crlf --upgrade
```

**Comment by bermudaparty** [comment]
Ok, I ran the upgrade (just this one command, nothing else) and then again my test.do.

### Unrelated Error
First I ran into the following error (reported in Atom). Which had previously not happened (and I don't think I've tampered with anything since yesterday).
```
Traceback (most recent call last):
File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec)
File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code exec(code, run_globals)
File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\stata_kernel__main__.py", line 4, in IPKernelApp.launch_instance(kernel_class=StataKernel)
File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance app.initialize(argv)
File "", line 2, in initialize File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error return method(app, args, **kwargs)
File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel\kernelapp.py", line 476, in initialize self.init_kernel()
File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel\kernelapp.py", line 387, in init_kernel user_ns=self.user_ns,
File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\traitlets\config\configurable.py", line 412, in instance inst = cls(args, **kwargs)
File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\stata_kernel\kernel.py", line 33, in init self.stata = StataSession(self, self.conf)
File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\stata_kernel\stata_session.py", line 76, in init if (platform.system() == 'Windows') and (int(self.stata_version[:2]) < ValueError: invalid literal for int() with base 10: '. '
```

As a quick fix I went in and changed line 76 in `stata_session.py` to (since I know my stata version is 13):

```
        if (platform.system() == 'Windows') and (int(13) <
                                                 15):
```
## Cut off letters
After this the basic communication to Stata seems to be working again. However there is still  a problem with letters being cut off. It seems now it's always the first letter on the first line of a block of code that gets lost.

Stata output:
```
. d `"D:\mydrive\Dummy"'
"D:\mydrive\Dummy invalid name
r(198);

. set more on

. set pagesize 100

. set linesize 80

. clear all

. global stata_kernel_graph_counter = 0

. `finished_init_cmd'
.  i "`c(stata_version)'"
unrecognized command:  i
r(199);

. `done'
.  StataKernelCompletions
unrecognized command:  StataKernelCompletions
r(199);

. `bcc4869c9c119320f7af8a3981776720'
.  nclude C:/Users/username/.stata_kernel_cache/include.do
unrecognized command:  nclude
r(199);

. `d153f7e92925be994646fb8d0cd93cab'
.  StataKernelCompletions
unrecognized command:  StataKernelCompletions
r(199);

. `bcc4869c9c119320f7af8a3981776720'
```

**Comment by kylebarron** [comment]
I edited code that should fix the first issue.

I changed it to try adding a `\r` before every line. Can you test again?

**Comment by kylebarron** [comment]
Manually adding empty spaces for all lines 63-70 _shouldn't_ work because that text is passed through `dedent()` which means that all common leading whitespace on those lines is removed. Do you have different numbers of spaces on each line?

**Comment by bermudaparty** [comment]
Oh, interesting. I'm afraid my understanding of python is quite rudimentary..

I did like this:
```
        init_cmd = """\
            adopath + `"{0}"\'
             cd `"{1}"\'
             set more on
             set pagesize 100
             set linesize {2}
             clear all
             global stata_kernel_graph_counter = 0
             `finished_init_cmd'
            """.format(adodir, os.getcwd(), self.linesize).rstrip()
```

But on a (for me) more exciting note, the following works (line 182):
`text = '\r' + '. ' + text`

I then get the below output in stata on executing my little test.do. Also adding more commands works fine. On the other hand, only `text = '\r' + ' ' + text` does not work.

```

. cd `"D:\myfolder\Dummy"'
D:\myfolder\Dummy

.  set more on

.  set pagesize 100

.  set linesize 80

.  clear all

.  global stata_kernel_graph_counter = 0

.  `finished_init_cmd'

.   di "`c(stata_version)'"
13

. `done'
.   _StataKernelCompletions
%varlist%

%globals%
stata_kernel_graph_counter S_ADO S_level F1 F2 F7 F8 S_StataMP S_StataSE S_FLAVO
> R S_OS S_OSDTL S_MACH
%scalars%

%matrices%


. `bcc4869c9c119320f7af8a3981776720'
.   mata : invtokens(st_dir("local", "macro", "*")')
  

. `08a286cef0dc100f5df674f2b5353f29'
.   include C:/Users/username/.stata_kernel_cache/include.do

. set obs 10000
obs was 0, now 10000

.   generate u1 = runiform()

. . `d153f7e92925be994646fb8d0cd93cab'
.   _StataKernelCompletions
%varlist%
u1
%globals%
stata_kernel_graph_counter S_ADO S_level F1 F2 F7 F8 S_StataMP S_StataSE S_FLAVO
> R S_OS S_OSDTL S_MACH
%scalars%

%matrices%


. `bcc4869c9c119320f7af8a3981776720'
.   mata : invtokens(st_dir("local", "macro", "*")')
  

. `08a286cef0dc100f5df674f2b5353f29'

```

**Comment by kylebarron** [comment]
> I did like this
That adds a space to all the lines _after_ the first one, since the latter ones are indented one space more than the first.

I'm guessing you could remove the `\r` and just have `'. ' + text`. But I think in more modern versions of Stata, then you would have two periods. I might figure out a way on Windows to only change this behavior on Stata 13 and earlier.

Note to self:
specifically, search the registry and use that to find which Stata version is installed.

**Comment by kylebarron** [comment]
@bermudaparty keep playing around using `text = '\r' + '. ' + text` and let me know if that works smoothly for you.

**Comment by kylebarron** [comment]
@bermudaparty 
A friend of mine had an old copy of Stata 13 for Windows, but I can't reproduce your issue:
![image](https://user-images.githubusercontent.com/15164633/45192005-005d3a80-b214-11e8-8c66-b0e78e5031ef.png)

**Comment by bermudaparty** [comment]
@kylebarron 
I tried uninstalling and reinstalling to see if it would then work for me too. I figured since I kinda messed up on my first install because I misunderstood the stata path warning message maybe it was actually me who changed something when trying to "fix" that non-issue.

And indeed, it now works out of the box for me too. But it seems that you changed some stuff anyway since your last comment? (1) I can't find `text = '\r' + text` anymore. (2) Running commands in Atom now doesn't open a Stata window anymore, whereas previously it did.

I uninstalled by running `pip uninstall stata_kernel` and deleting the .conf file.

---

On another note: When installing again I got the following error (which I quick-fixed by simply removing the { and } from install.py).

```
stata_kernel\install.py", line 82, in install_conf
    """.format(stata_path, execution_mode))
ValueError: Single '}' encountered in format string
```

**Comment by kylebarron** [comment]
> I can't find `text = '\r' + text` anymore.

That's because this was added under a specific branch of code. That's why I had asked you to do `pip install git+https://github.com/kylebarron/stata_kernel@windows-crlf --upgrade`.

> Running commands in Atom now doesn't open a Stata window anymore, whereas previously it did.

Likewise this is a change in the master branch.

> When installing again I got the following error

This is a bug; I should really test running `install.py` along with other automated tests...

**Comment by kylebarron** [comment]
I fixed the installing bug.

Good to hear it's working for you. Reopen if you have more issues.

**Comment by bermudaparty** [comment]
I listed these observations because it seemed weird to me to just say "the bug never existed" simply because I wasn't able to reproduce it in a newer version. So I did a small experiment, and voilà:

If i revert to `self.automate(cmd_name='UtilShowStata', value=2)` (#131)  the behavior is back as it was when I opened this issue. I figured this might be useful information to you. No need to reopen for my sake though.

Thanks for your support and the whole project!



(Also, thanks for clarifying about `text = '\r' + text`. I was aware that you made me install from another branch, but not that that line had only been in there. Although in hindsight it makes sense that having `text = text` before adding `'\r' +` would have been pointless.. :) .)

**Comment by kylebarron** [comment]
So if the only thing you change is `1` to `2` in `self.automate(cmd_name='UtilShowStata', value=2)`, the problem returns?

**Comment by bermudaparty** [comment]
Yes

**Comment by kylebarron** [comment]
Well in that case the error is in Stata's automation code. It's good this works, but in general I think I won't spend much effort to try to support Stata 13 and earlier.
