### ISSUE TITLE
clarify warning when install.py can't find  stata_path

### ISSUE THREAD

**Issue by bermudaparty** [kylebarron/stata_kernel#128]
**Is your feature request related to a problem? Please describe.**
Currently the documentation (and error that is shown in `install.py` when the `stata_path` is not found) make it seem like manually adding the path to the config file will then make the install script read this path when trying to install again.

This is however not the case. The installer will even overwrite the manually changed config file when running it again.

**Describe the solution you'd like**
I'm not sure what the intended behavior here is. But to me (reading the documentation) what I would expect and what would make sense is if `_find_path()` went something like this:
```
    ...
        if fpath:
                break

    if fpath == '':
        (read path from config)
    return fpath
```
**Describe alternatives you've considered**
Change the documentation to represent the current behavior.

**Comment by kylebarron** [comment]
I should make it clearer, but the intended behavior is that the `python -m stata_kernel.install` only gets run _once ever_.

**Comment by kylebarron** [comment]
Even if you do `pip install stata_kernel --upgrade`, you never need to do the second step again. That second step is basically just to register the Stata kernel with Jupyter so that Jupyter knows it exists.

**Comment by Gkreindler** [comment]
I also got confused by the same thing! I thought the install failed and was puzzled by it overwrites the config file. A message like the following would help I think: 

"Installation complete. Please add the path manually to the config file (+do not run this command again or the config file will be overwritten!) "
