### ISSUE TITLE
[long sequence] is unrecognized r(199) error produced

### ISSUE THREAD

**Issue by jeremyfreese** [kylebarron/stata_kernel#132]
Sorry, not knowledgeable about how to provide bug report in format you want.  I am using version 1.4.3., which I downloaded today (first time using it).  I have looked at it both in Atom and Jupyter Notebooks.  I can get a few lines to run, and then will start getting an error message like:

. c4869c9c119320f7af8a3981776720'
command c4869c9c119320f7af8a3981776720 is unrecognized
( )
r(199);

Commands will still run, although they will halt on that line, so that for example "display 2+2" in Atom produces:

. c4869c9c119320f7af8a3981776720'
command c4869c9c119320f7af8a3981776720 is unrecognized
4
r(199);

Once I start getting this error (which happens within a few commands), I don't un-start getting it.  In Jupyter, I was able to start fresh by resetting the kernel, but I don't know how to do that in Atom (and, in any event, would only work for a few lines).

**Comment by kylebarron** [comment]
- What OS are you using and what version of Stata are you using?
- Is there a sequence of commands that you start with that _always_ produces that?

There is supposed to be a `` ` `` character before the `c4869`. Running something like 
```stata
`c4869c9c119320f7af8a3981776720'
```
in Stata does nothing in Stata but when it appears in the log file it tells this package that your command has ended. So I need to figure out why the `` ` `` is missing.

**Comment by jeremyfreese** [comment]
I'm using a Mac and Stata 15.1 MP.  Plausibly it starts when I am executing
a use statement that has a quotation mark, which would be a common form for
an error involving failing to read a ' or ` in properly.  Will see if I can
poke around more to nail this down.

**Comment by kylebarron** [comment]
Do you know if you're using `console` or `automation` mode?

Did you adjust the configuration file? By default on Mac it uses `console` mode. Does a Stata window flash when you start the kernel? If not you're using `console` mode. Would you be able to share the log file at `$HOME/.stata_kernel_cache/console_debug.log`?

**Comment by jeremyfreese** [comment]
So, it isn't the quotation marks in the use statement.  The attached
screenshot (with no quotes anywhere) is perhaps a telling bit, and fits the
general issue where things start to go awry with the use statement.  Note
the ominous "(  )".  When I execute any statement after the attached, I'll
get the message.

I have not changed the config file from whatever it is upon install.  I
will attach the console_debug_log file.

**Comment by kylebarron** [comment]
Sorry, the screenshot doesn't appear to have made it through the email reply. Try going to Github here: `https://github.com/kylebarron/stata_kernel/issues/132` and pasting/uploading the screenshot there.

**Comment by jeremyfreese** [comment]
[console_debug.log](https://github.com/kylebarron/stata_kernel/files/2355050/console_debug.log)
<img width="615" alt="screenshot 2018-09-05 17 04 03" src="https://user-images.githubusercontent.com/5857433/45128712-61addc80-b134-11e8-932e-7a683de3c4a3.png">

**Comment by jeremyfreese** [comment]
(Sorry, hit wrong button and accidentally closed.)

**Comment by kylebarron** [comment]
Thanks. This is very helpful. This actually stems from a known issue (#103); we currently have some troubles correctly parsing `more`.

After every command, the kernel silently lists all the variables in memory, which allows the kernel to provide autocomplete using the current environment. Since you loaded a very wide dataset, listing all the variables in memory hit `--more--`. 

I _think_ I fixed this specific issue, but it would be great if you could try it out before I push out the fix to pip.

Can you run in the terminal
```
pip install git+https://github.com/kylebarron/stata_kernel@dev-ado-fixes --upgrade
```
(You don't have to run `python -m stata_kernel.install` again). Then try running the Stata code again?

**Comment by kylebarron** [comment]
I pushed a new version to the Python package index with what I think should fix your issue.

You can just run in your terminal
```
pip install stata_kernel --upgrade
```
(You don't have to run `python -m stata_kernel.install` again). Then try running the Stata code again and let me know if it works!

**Comment by jeremyfreese** [comment]
(Thanks.  Sorry I was out last night and wasn't able to test the earlier
version you'd sent.)

**Comment by kylebarron** [comment]
No worries! The fixes were beneficial regardless of whether they fixed your problem.

Please do let me know if it does work for you.

**Comment by jeremyfreese** [comment]
Works great!

**Comment by kylebarron** [comment]
Great to hear!
