### ISSUE TITLE
Expand linesize past 80 by default. Maybe to 100 or 120?

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#138]
Mention in docs that you can use `set linesize` to make it wider? Should there be a `%set` setting for this?

**Comment by mcaceresb** [comment]
Isn't `set linesize` better than `%set linesize`? It's 7.7% shorter! Must be between 40 and 255.

**Comment by kylebarron** [comment]
Yes but there's an internal `self.linesize` setting that is currently used when parsing log lines. 

Potentially that could be changed through fixing #120 / #139.

**Comment by mcaceresb** [comment]
Shouldn't that equal the output of `` `:set linesize'``? Relying on `%set` would miss whenever the user does `set linesize` (also, if you're relying on linesize, how do you deal with line-size changes within do files or programs?)

**Comment by kylebarron** [comment]
At this point, it just assumes the linesize will not be less than 75. If the line size is greater, it will work just fine. But if the line size is smaller that's an issue. The second screenshot of https://github.com/kylebarron/stata_kernel/issues/125 was caused by `linesize` decreasing when the Stata window was manually resized. That was fixed by completely hiding the main Stata gui window on Windows.

**Comment by kylebarron** [comment]
> also, if you're relying on linesize, how do you deal with line-size changes within do files or programs?

At this point, I only use `linesize` to remove code lines. If you run `helloworld`, and that user-defined program changes the `linesize`, that's fine because no new code lines are sent to Stata within that program. And it would have already correctly remove the line 
```
. helloworld
```
