### ISSUE TITLE
Can't run Stata commands from BAT file

### ISSUE THREAD

**Issue by tlcaputi** [kylebarron/stata_kernel#141]
#### Problem description

- I can't use a .BAT file in Windows to insert commands into Stata. 

For example, the following .BAT file doesn't actually run the regression.

    ```
    jupyter console --kernel stata
    sysuse auto
    reg price mpg
     
    ```

It just gets to:

    ```
    jupyter console --kernel stata
    In[1]: 
    ```

and stops.

#### Expected Output

    ```
    c:\Users> jupyter console --kernel stata
    In [1]: sysuse auto
(1978 Automobile Data)

In [2]: reg mpg price
      Source |       SS           df       MS      Number of obs   =        74
-------------+----------------------------------   F(1, 72)        =     20.26
       Model |  536.541807         1  536.541807   Prob > F        =    0.0000
    Residual |  1906.91765        72  26.4849674   R-squared       =    0.2196
-------------+----------------------------------   Adj R-squared   =    0.2087
       Total |  2443.45946        73  33.4720474   Root MSE        =    5.1464
------------------------------------------------------------------------------
         mpg |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       price |  -.0009192   .0002042    -4.50   0.000    -.0013263   -.0005121
       _cons |   26.96417   1.393952    19.34   0.000     24.18538    29.74297
------------------------------------------------------------------------------

    ```

#### Other information

If you didn't attach the debugging log, please provide:

- Operating System: Windows 10
- Stata version: StataMP-64 version 15
- Package version (You can find this by running `pip show stata_kernel` in your terminal.)

Name: stata-kernel
Version: 1.4.4
Summary: A Jupyter kernel for Stata. Works with Windows, macOS, and Linux. Preserves program state.
Home-page: https://github.com/kylebarron/stata_kernel
Author: Kyle Barron
Author-email: barronk@mit.edu
License: GPLv3
Location: c:\users\tcapu\anaconda3\lib\site-packages
Requires: IPython, jupyter-client, beautifulsoup4, pygments, pillow, pandas, ipykernel, regex, pexpect
Required-by:

**Comment by kylebarron** [comment]
It's not possible to do this. `jupyter console --kernel stata` starts an interactive command prompt. At least from Mac/Linux using Bash, those commands would first start the interactive session of Stata, then _after that first command finishes_ it runs the latter commands. 

Bash trying to run the commands after exiting the jupyter console:
![image](https://user-images.githubusercontent.com/15164633/45171595-d0407800-b1d0-11e8-8434-0d25879e42fa.png)

If you want to be running commands programmatically, you should be [calling Stata from batch mode](https://www.stata.com/support/faqs/windows/batch-mode/).
