### ISSUE TITLE
Missing newlines

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#144]
@mcaceresb 
> Is this issue (#111) what causes 
> ```
> disp _n(10) "hi" _n(10) "bye"
> ```
> To eat all the newlines?

The issue here is that I expect for `\n`, so there are no `\n`s in the result lines, and then I only display a result using `if res`. So '^\n' gets expected to '' and the `bool` of that is `False`.

Of course displaying those newlines can be desirable, but I don't want to display newlines for lines I sent to Stata. So I think I'll have to change the code here a bit:
https://github.com/kylebarron/stata_kernel/blob/2438b515d1ef314cc3fd6165d9d575b030ffdc3b/stata_kernel/stata_session.py#L256-L266

**Comment by mcaceresb** [comment]
Well, it also affects #117 since the resulting code looks odd with so many missing newlines.

> I don't want to display newlines for lines I sent to Stata

You mean `you` to be the kernel, as opposed to lines the user sends?

**Comment by kylebarron** [comment]
No I mean if you send `di "hi"`, the first line caught by `\n` would be `. di "hi"` and the second would be `hi`. The code sees that the first matches the code line sent to Stata, but I currently just change the result to `res=''`. And I don't want to show a newline for that because it is produced from a code line and not a result line. 

It shouldn't be a complicated change to fix, but it is a change
