### ISSUE TITLE
Remove line continuations in results sent to frontend

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#151]
1. Keep track of `` `c(linesize)'``
2. If there are `` `c(linesize)'`` characters on a line, don't send it back to the user yet. Wait for the next line; if the next line starts with `> `, iterate. When a line doesn't have `` `c(linesize)'`` characters or the next line doesn't start with `> `, return concatenated text to user.

Maybe have a setting for whether to perform this, but I think the console environment will automatically wrap text, and it's fine for notebooks and Hydrogen to have a scrolling div. 

This would be much closer to how other languages return results.

In Hydrogen this would also facilitate copy-pasting of results:
![image](https://user-images.githubusercontent.com/15164633/45241045-d27e0180-b2b8-11e8-923c-f9932298c4d5.png)

**Comment by kylebarron** [comment]
> Not sure that this can handle line size changes across do files or programs, right?

A simpler implementation would be: don't send line 1 until line 2 comes in and it doesn't start with `> `, or you hit the ending marker. This would get tripped up if people start lines with `> ` all the time, however.

How often does the line size change within programs? I've never set it...

But yeah putting this in a setting would be fine.

**Comment by mcaceresb** [comment]
> I've never set it...

I mean, half my programs start with `set more off` and `set linesize`, but the latter largely because small linesizes get annoying for some messages. If I ever want to print something long I break it up anyway...

I think it's a good idea, so I'd vote to have it on by default but the user can decide which behavior they prefer, right? If someone's setting linesize I reckon they might be fine tuning this setting also.

**Comment by kylebarron** [comment]
> If someone's setting linesize I reckon they might be fine tuning this setting also.

True

**Comment by kylebarron** [comment]
Do you have a preference over 
1. using linesize and only checking for continuations if there are linesize number of characters
2. always checking for `> ` on the next line

**Comment by mcaceresb** [comment]
Well, it's tricky, right? because a line might end in a space and be a legitimate continuation. I'd say only do it if it's preceded by a line that starts with `>` or a non-blank line.

**Comment by mcaceresb** [comment]
You could also have a space tolerance. If the previous line ends with something like fewer than 2 consecutive spaces and starts with `>` then delete otherwise assume the previous line ended.

**Comment by kylebarron** [comment]
> because a line might end in a space and be a legitimate continuation

I _think_ but need to check that if a line ends in a space, that space character will be included before the `\r\n`.

**Comment by kylebarron** [comment]
So I don't think it'll just be 

`lastchars\r\n`

I think it'll be

`lastchars   \r\n`

**Comment by kylebarron** [comment]
![image](https://user-images.githubusercontent.com/15164633/45242481-33f49f00-b2be-11e8-91b2-e123d9fadee0.png)
This is the case using pexpect with a console. Need to check it's the same on Windows, but this means that even if the 80th character is a space, I'd still see it and know that the line hit the line size.

**Comment by mcaceresb** [comment]
Oh, cool, then always check the line size.

**Comment by kylebarron** [comment]
Knowing all text on the line before sending to the frontend would be very helpful and would help solve #162 and #177. But you're right that I would never know if linesize changed within a program.

**Comment by kylebarron** [comment]
I'm going to close this because I don't think it's worth my time and I plan to attempt a different way to solve #177
