### ISSUE TITLE
Fuzzy matching for autocomplete

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#159]
Personally I really like fuzzy matching over straight matching because of my fat fingers. Instead of creating string distances ourselves, it would be easy to use something like https://github.com/seatgeek/fuzzywuzzy.

Allow this as a config setting.

**Comment by mcaceresb** [comment]
Presumably there's overhead? Or is this smart (i.e. only use the engine if the match is not exact)?

**Comment by kylebarron** [comment]
I think there would be some overhead. I just don't know how much

**Comment by kylebarron** [comment]
It depends on the sizes of the sets presumably.
