### ISSUE TITLE
Can not use Chinese Characters when using Use the new Stata Jupyter kernel with Atom's Hydrogen package

### ISSUE THREAD

**Issue by LulinS** [kylebarron/stata_kernel#161]
When my code contains Chinese Characters, it reports: 
> UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 75-76: invalid continuation byte

The detail description is that when I draw one picture using command line, the first picture goes well. However, when I run the second command, this does not work, and report the above error. Then, I rerun the first command, it goes well. Strangely, the second picture that I want to draw comes out together.

My command is like this:
```
line mcar car100 car300 trddt, ytitle("CAR(等权)") xtitle("交易日") legend(label(1 "A股") label(2 "Top100") label(3 "Top300"))

line wcar wcar100 wcar300 trddt, ytitle("CAR(市值加权)") xtitle("交易日") legend(label(1 "A股") label(2 "Top100") label(3 "Top300"))
```
The full message is like this:
> [IPKernelApp] ERROR | Exception in message handler: Traceback (most recent call last): File "/Applications/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell handler(stream, idents, msg) File "/Applications/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request user_expressions, allow_stdin) File "/Applications/anaconda3/lib/python3.6/site-packages/stata_kernel/kernel.py", line 81, in do_execute text_to_run, md5, text_to_exclude=text_to_exclude) File "/Applications/anaconda3/lib/python3.6/site-packages/stata_kernel/stata_session.py", line 195, in do rc, res = self.expect(text=text, child=child, md5=md5, **kwargs) File "/Applications/anaconda3/lib/python3.6/site-packages/stata_kernel/stata_session.py", line 242, in expect match_index = child.expect(expect_list, timeout=None) File "/Applications/anaconda3/lib/python3.6/site-packages/pexpect/spawnbase.py", line 341, in expect timeout, searchwindowsize, async_) File "/Applications/anaconda3/lib/python3.6/site-packages/pexpect/spawnbase.py", line 369, in expect_list return exp.expect_loop(timeout) File "/Applications/anaconda3/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop incoming = spawn.read_nonblocking(spawn.maxread, timeout) File "/Applications/anaconda3/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking return super(spawn, self).read_nonblocking(size) File "/Applications/anaconda3/lib/python3.6/site-packages/pexpect/spawnbase.py", line 178, in read_nonblocking s = self._decoder.decode(s, final=False) File "/Applications/anaconda3/lib/python3.6/codecs.py", line 321, in decode (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 75-76: invalid continuation byte

The version of my stata_kernel is 1.4.8 on the Mac OS.

**Comment by kylebarron** [comment]
Reproducible with
```stata
sysuse auto
scatter price mpg weight length, ytitle("CAR(等权)") xtitle("交易日") legend(label(1 "A股") label(2 "Top100") label(3 "Top300"))
scatter mpg price weight length, ytitle("CAR(市值加权)") xtitle("交易日") legend(label(1 "A股") label(2 "Top100") label(3 "Top300"))
```

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/kyle/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/kyle/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/kyle/github/stata/stata-kernel/stata_kernel/kernel.py", line 81, in do_execute
    text_to_run, md5, text_to_exclude=text_to_exclude)
  File "/Users/kyle/github/stata/stata-kernel/stata_kernel/stata_session.py", line 202, in do
    rc, res = self.expect(text=text, child=child, md5=md5, **kwargs)
  File "/Users/kyle/github/stata/stata-kernel/stata_kernel/stata_session.py", line 249, in expect
    match_index = child.expect(expect_list, timeout=None)
  File "/Users/kyle/anaconda/lib/python3.6/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/Users/kyle/anaconda/lib/python3.6/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/Users/kyle/anaconda/lib/python3.6/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/Users/kyle/anaconda/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/Users/kyle/anaconda/lib/python3.6/site-packages/pexpect/spawnbase.py", line 178, in read_nonblocking
    s = self._decoder.decode(s, final=False)
  File "/Users/kyle/anaconda/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 75-76: invalid continuation byte
```

**Comment by kylebarron** [comment]
I'd never tested out Chinese characters before. It appears that Stata behaves a bit differently when using them. It may take a few days to resolve.

**Comment by kylebarron** [comment]
This is the specific issue
![image](https://user-images.githubusercontent.com/15164633/45496896-6da52a00-b744-11e8-9570-f177ac77c2da.png)

**Comment by mcaceresb** [comment]
I wonder at what point this issue gets triggered.

```stata
sysuse auto
scatter price mpg, ytitle("CAR(等权)") xtitle("交易日") legend(label(1 "A股") label(2 "Top100") label(3 "Top300"))
scatter mpg price, ytitle("CAR(市值加权)") xtitle("交易日") legend(label(1 "A股") label(2 "Top100") label(3 "Top300"))
```

doesn't give me an error, for instance (though it does throw the log parsing out of sync).

**Comment by kylebarron** [comment]
Yeah there are two issues here. 

One is the log parsing. I'm using #162 to consolidate that. That has known cause and fix. 

The other is the UnicodeDecodeError. I don't know what causes this. @mcaceresb are you using the same CJK characters as the example?

**Comment by mcaceresb** [comment]
Yes, I just took out some variables from the scatter. If I put them back I do get the error.

**Comment by kylebarron** [comment]
> If you just want to avoid the error, you can use encoding='utf-8', codec_errors='replace' to turn unknown bytes into the unicode replacement character. This will lose data, though.

https://github.com/pexpect/pexpect/issues/381

**Comment by mcaceresb** [comment]
Mmm... Not 100% what data gets lost. Does that mean unicode characters are read correctly but non-unicode encoded characters are not? If Stata takes wide unicode characters and modifies them somehow to fit a column then it might be a problem if the character gets changed...

**Comment by kylebarron** [comment]
I added `codec_errors='replace'` and you can see the original issue. It appears that when a 2-byte character ends the line, Stata console will send the first byte on one line and the second byte on the next. Hence the `?` symbols.

![image](https://user-images.githubusercontent.com/15164633/45526581-b7722c80-b7a5-11e8-844e-641c28f662fb.png)

Currently, we pass `encoding='utf-8'` to `pexpect.spawn()`. If we want this to be entirely accurate, we'd probably need to remove this and communicate with `pexpect` in terms of bytes. What do you think about this @mcaceresb?

**Comment by kylebarron** [comment]
The same issue is clear in the Stata console... This is just something we'll have to work around if we want to support CJK characters. It's conceivable to just not display characters that are split over line breaks correctly. But not ideal.
![image](https://user-images.githubusercontent.com/15164633/45526904-2b610480-b7a7-11e8-9fa8-ba371c521674.png)

**Comment by mcaceresb** [comment]
> If we want this to be entirely accurate, we'd probably need to remove this and communicate with pexpect in terms of bytes.

Not sure how that would work?

**Comment by kylebarron** [comment]
Basically we'd

- monitor `c(linesize)` and if that number of bytes are on the line, check if there's a line continuation on the next line. If there is, remove that line continuation _before_ encoding to UTF-8. That way the two halves of a CJK character could be joined before the encoding, and they'd display correctly.

**Comment by kylebarron** [comment]
I think the best course of action is to change to `codec_errors='replace'` in the next release so that most functionality works. Then in the longer term, we can think of how to improve this kind of encoding.
