### ISSUE TITLE
Use ANSI escape codes with console/qtconsole

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#163]
Jupyter console and qtconsole support the use of ANSI escape codes to "format" text. See https://github.com/jupyter/qtconsole/issues/273. Apparently bold only works in the console and not qtconsole, though underline works in both.

We could use this to display somewhat-formatted help in (qt)console. Though it might be too much effort. 

What do you think @mcaceresb?

![image](https://user-images.githubusercontent.com/15164633/45435664-fb1e4680-b67e-11e8-9938-388e90c40c0b.png)

![image](https://user-images.githubusercontent.com/15164633/45435637-f2c60b80-b67e-11e8-9a56-a9a31bb47a18.png)

List of ANSI escape codes: https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences

**Comment by mcaceresb** [comment]
Too muh effort, tbh. We'd have to parse the help file with no API. If pandoc has a html to ASCII escapes, on the other hand...

**Comment by mcaceresb** [comment]
Is that feasible? I suppose if you're just doing italics, bold, and underline maybe... Now that you mention it, is there a lot more than that in the HTML files? I guess all the formatted tables and lines, but that wouldn't translate into ANSI codes anyway, right?

**Comment by kylebarron** [comment]
Yeah it's pretty much just italics, bold and underline
