### ISSUE TITLE
Just some ideas about %labels

### ISSUE THREAD

**Issue by stevencollinscn** [kylebarron/stata_kernel#165]
In case that you're interested in creating a new magic command %labels like we talked about last time, I wanna share some ideas about what I usually do: 

```
import pandas as pd
# getting all the labels as a dict
dict = pd.read_stata('dataset.dta', iterator=True).variable_labels()
# storing the labels as a new dataframe
metadata = pd.DataFrame.from_dict(dict, orient='index', columns=['labels'])
# using .loc to check labels if needed
metadata.loc['var_name']
```
Hopefully, this will help.

**Comment by kylebarron** [comment]
Except for a small portion of the data when you type `%browse` or `%head`, the data is never in Python. I don't want to ever move the data to Python, because that's slow.

**Comment by stevencollinscn** [comment]
Then I think `describe` is the answer.

**Comment by kylebarron** [comment]
I agree. But then it's ideal for the user to type that instead of making a new magic to remember.

**Comment by stevencollinscn** [comment]
indeed. btw, Jupyter lab cannot export a pdf at this moment for Stata, right?

**Comment by kylebarron** [comment]
It should be able to. Jupyter Notebook can.

**Comment by stevencollinscn** [comment]
<img width="618" alt="snipaste_2018-09-13_16-07-53" src="https://user-images.githubusercontent.com/33796896/45512919-3435e400-b76f-11e8-9283-c9f1a9556474.png">
any idea why?

**Comment by kylebarron** [comment]
By default, stata_kernel exports SVGs. When you export to PDF, Jupyter tries to use LaTeX to convert to PDF. LaTeX can't use SVGs. Therefore, the SVGs need to be converted.

Download [inkscape](https://inkscape.org/en/) and it'll work.

**Comment by mcaceresb** [comment]
Perhaps inspect for variables could show their label? I think we talked about this at some point. Not 100%.

**Comment by mcaceresb** [comment]
I had a different thought in mind: Inspection is mainly useful because it is a way to look something up without having to go to a separate line to look it up. So if inspect shows variable labels, you could type Shift + Tab (in notebooks) anywhere and see a tool-tip with the variable description (as long as the cursor is at or by a variable).

**Comment by kylebarron** [comment]
I'm following this issue (https://github.com/nteract/hydrogen/issues/371) on Hydrogen, because it would be really nice if Atom also made inspection a tooltip and not a separate pane.
