### ISSUE TITLE
Send (svg or png) AND (pdf) image representations to frontend

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#175]
## Overview 
The quagmire of image formats is such:

### SVG

**Pro**
- Vector format
- Low file size
- Viewable in all rich frontends

**Con**
- Can't be used with LaTeX without converting
- Can't be created with earlier versions of Stata

### PDF

**Pro**
- Possible to create on any platform and any version of Stata
- Vector format
- Low file size
- Can be exported to LaTeX without conversion

**Con**
- Not viewable in _any_ frontend

### PNG

**Pro**
- Possible to create in earlier versions of Stata
- Viewable in all rich frontends

**Con**
- Not vector image format
- Can't be created on Linux

## Proposal

I propose that `stata_kernel` always returns both the (SVG or PNG) _and_ the PDF representation of all images back to the frontend.

1. When multiple mimetypes of the data are sent to Jupyter Notebook, it chooses which to show based on an internal preference hierarchy of mimetypes. But crucially, it doesn't discard alternate data. So when I send a `display_data` object that has _both_ `image/svg+xml` _and_ `application/pdf` mimetype objects, both are stored inside the `.ipynb` file. This means that when I export the Notebook to an HTML file, it uses the SVG version, but when I export to a PDF, it uses the PDF version of the image and doesn't touch the SVG data.

  This means that on a Linux server without inkscape, I was able to view the SVG image in the Notebook and in the exported HTML, but I was still able to compile a LaTeX document with the image:
![image](https://user-images.githubusercontent.com/15164633/45577105-6109fa00-b848-11e8-84df-4292bec517d1.png)

2. Time to export an already-created image is negligible. With `rmsg` on, the time to export an SVG or PDF never reached 0.01s, for PNG it was between 0.02 and 0.04s. So the marginal time cost of exporting the PDF as well should be negligible.
3. Image sizes are small. For the export of `scatter price mpg`, the PDF was 9.7KB, the SVG was 16KB, and the PNG was 22KB.

**Comment by kylebarron** [comment]
@mcaceresb

**Comment by mcaceresb** [comment]
> Time to export an already-created image is negligible.

I'd caution against believing this too much. Exporting an image that doesn't have a ton of info in it certainly doesn't take too long. If you make a histogram from 10M obs, it's very comparable to one from 1k obs because in both cases you are exporting a few dozen bars, the axes, titles, labels, etc. None of that is too taxing. However, the more complex the graph the more complex the export. An exaggerated example to illustrate the point:

```stata
clear
tempfile test
sysuse auto
keep price mpg
expand 10000
scatter price mpg
replace price = price + 100 * runiform()
graph export `test'.svg, as(svg)
graph export `test'.pdf, as(pdf)
```

The svg export takes 6 seconds and the pdf export takes 35. The svg image is 177MiB in size and the pdf is 36MiB. You can think of this as a corner case, but my point is that turning off the graph redundancy should be an option.

Tbh, png would be my choice if it was available in the console version (GUI can make PNGs just fine btw). The 2nd best idea does seem to be doing the pdf + svg, but, as I said, I would worry a bit more about how much space and time this could end up taking (i.e. include an option to turn off the redundancy).

**Comment by kylebarron** [comment]
Very valid points. Yet again why having your input is so helpful.

(I assume you meant for the scatter to be after the replace?)

On my 5 year old laptop, exporting the svg took 43 seconds and the pdf took 40 seconds, and file sizes are 117MB and 35MB respectively.

- Nbconvert (the Jupyter component that exports to different formats) will automatically convert SVGs to PDF when creating a PDF, but that requires inkscape to be installed, which is a very heavy dependency.
- Do you think the graph redundancy should be on by default?
- Do you think there should only be redundancy for SVG, or also for PNG? You can use PNG files in LaTeX, right? Though they might not look as nice cause they're raster...?

**Comment by mcaceresb** [comment]
I was going to suggest a converter (e.g. cairosvg, imagemagick, etc.) but the memory use is, frankly, ridiculous: several GiB for a 100MiB svg image. I think if the size of the svg object is greater than 5MiB or whatever we can warn the user their images will generate a very large cache. (I guess stuff like this is why `%matplotlib` is not inline by default?)

For the redundancy...yes, I do think it should be on by default wherever we end up putting SVGs as default. Perhaps it would be better to use PNGs in Windows (and OSX if the console can export PDFs there)?

My reasoning is that silent failures are worse than annoying warnings: There is no flag for detecting a notebook, so if a user makes a notebook, has all their images, and tries to export it and is met with this issue, we can't necessarily tell them how to fix it (they'd have to look it up, right?). Moreover, if the images took some time to generate it will be quite unpleasant to ask them to re-run it.

A (qt)console or hydrogen user trying to see an image will probably be running stuff interactively anyway, and if we print a warning about large cache files they can turn that off and continue working normally.

**Comment by kylebarron** [comment]
> I was going to suggest a converter (e.g. cairosvg, imagemagick, etc.) but the memory use is, frankly, ridiculous: several GiB for a 100MiB svg image

I wouldn't have guessed memory use would be that high.

> I think if the size of the svg object is greater than 5MiB or whatever we can warn the user their images will generate a very large cache. (I guess stuff like this is why %matplotlib is not inline by default?)

That's a good idea. Additionally, when someone saves an `.ipynb` file, _all_ data sent to the kernel is included within that file. This means that the file can be rendered, as with [nbviewer](https://github.com/jupyter/nbviewer) without any dependencies outside the file. But of course, if we send a 50MB svg and a 50MB pdf, a single graph will add 100MB to the size of the `.ipynb` file.

> and OSX if the console can export PDFs there

I assume you meant if the console can export PNGs. I just tried on macOS and also got a `translator Graph2png not found` error.

> Perhaps it would be better to use PNGs in Windows

My personal belief is that SVGs/vector graphics in general usually look much better than PNGs, and so SVGs should be the default where possible.

> I wouldn't worry too much about image quality in this case. I think the main purpose is illustrative; if a user wants to send an image they'd save it explicitly.

I don't entirely agree. I could definitely envision creating reports from a Jupyter Notebook. You don't have to worry about exporting the images and then loading them somewhere else. For people who have LaTeX installed but don't know/want to write their documents in it, it's really helpful to have the Notebook's one-click option to PDF. And in that case I definitely value image quality in the PDF.

> For the redundancy...yes, I do think it should be on by default wherever we end up putting SVGs as default.

Maybe have a setting for SVG redundancy turned _on_ by default and a setting for PNG redundancy turned _off_ by default? (I haven't checked if both a PNG and a PDF get sent to Jupyter, which is exported in the LaTeX PDF).

> My reasoning is that silent failures are worse than annoying warnings:
> 
> we can't necessarily tell them how to fix it (they'd have to look it up, right?)

Well it's not a silent failure. If the user tries to export SVGs to PDF and doesn't have inkscape installed, `nbconvert` displays this error in the web browser:
https://github.com/kylebarron/stata_kernel/issues/165#issuecomment-421136210
![](https://user-images.githubusercontent.com/33796896/45512919-3435e400-b76f-11e8-9283-c9f1a9556474.png)

**Comment by mcaceresb** [comment]
1MiB? I initially thought 5, but a few dozem pics would mean several hundred MiB in redundancy.

**Comment by kylebarron** [comment]
What percentage of SVG images do you think would be larger than 1MB?

**Comment by mcaceresb** [comment]
Very few tbh. Most are small, no?

**Comment by kylebarron** [comment]
I'm thinking 2MiB

**Comment by mcaceresb** [comment]
Sure.
