### ISSUE TITLE
Consider renaming? IStata?

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#18]

**Comment by stevencollinscn** [comment]
It doesn't seem Stata kernel has an icon displaying in Atom, like R or Python kernels. Are you considering adding one?

**Comment by stevencollinscn** [comment]
Maybe it' not an icon and just something at the buttom to display the status of the kernel. I just opened my Atom and checked. It seems that there is no status display in either Python or R anymore. Maybe it is removed, but if you go to hydrogen's page. You can still see it

![snipaste_2018-09-02_13-24-59](https://user-images.githubusercontent.com/33796896/44958836-b0990f00-aeb3-11e8-835d-c51fc74f4086.png)
