### ISSUE TITLE
Let %set use the same keys as the configuration

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#182]
@mcaceresb 
I think 
```
%set graph_format svg
```

is more straightforward to use than
```
%set graph --format svg
```

because `graph_format` is the key already used in the configuration file and listed in the [documentation](https://kylebarron.github.io/stata_kernel/getting_started/#graph-settings).

**Comment by mcaceresb** [comment]
Sure. Pretty sure the Stata convention is to allow `set graph format svg`, but I could be off. We don't have to do that tho.

**Comment by kylebarron** [comment]
Yeah that makes sense, but I think this method is simpler and easier for the package.
