### ISSUE TITLE
use a different log file for _StataKernelCompletions

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#194]
Might solve #154. Originally mentioned here: https://github.com/kylebarron/stata_kernel/issues/119#issuecomment-420367752

**Comment by mcaceresb** [comment]
Something like this, maybe? Can't really think of an elegant solution per se.

```stata
local tmplog foo
qui log query _all
local lognames
forvalues l = 1 / `r(numlogs)' {
    local lognames `lognames' `r(name`l')'
}
foreach logname of local lognames {
    if ( `"`logname'"' == "<unnamed>" ) {
        log off
    }
    else {
        log off `logname'
    }
}
log using `tmplog', name(`tmplog') text replace
disp "hi from `tmplog'"
_StataKernelCompletions
log close `tmplog'
foreach logname of local lognames {
    if ( `"`logname'"' == "<unnamed>" ) {
        log on
    }
    else {
        log on `logname'
    }
}
```

**Comment by kylebarron** [comment]
The main issue with this is that if I write to a different log file, I need to be reading another log file in Python. I'm not sure if that code segment covers that...

**Comment by mcaceresb** [comment]
Actually, I'm realizing that you don't need to redirect it to another log file bc this is redirected from the interaction with Stata, right?
