### ISSUE TITLE
Fail to display graphs from some third-party packages

### ISSUE THREAD

**Issue by alanzchen** [kylebarron/stata_kernel#197]
#### Problem description

Graphs from `vioplot` are not showing up in the output area. The code executed without problem. 

#### Debugging log

Data is private, so I am not allowed to disclose this log but please tell me if I should look for something in the log file.

#### Code Sample

```stata
vioplot price
```

#### Expected Output

A graph.

#### Other information

If you didn't attach the debugging log, please provide:

- Operating System: macOS Mojave
- Stata version 15.1
- Package version 1.5.4

**Comment by kylebarron** [comment]
Thanks. `vioplot` wasn't one of the keywords I looked for. Do you have any other user-generated graphing keywords I should add at the same time?

**Comment by alanzchen** [comment]
I haven't encountered the same problem with other packages/built-in functions so far. I'll add them here once I spot another one.

**Comment by kylebarron** [comment]
I added a setting for this so that the configuration can be updated with any user graph keywords. See https://kylebarron.github.io/stata_kernel/getting_started/#graph-settings. I also set `vioplot` and `coefplot` to the base list.

**Comment by alanzchen** [comment]
Thank you @kylebarron for the quick fix!

Can we have a magic (like `%graph`) for this, as the list will never be exhaustive?

**Comment by kylebarron** [comment]
That's basically what I added. The `user_graph_keywords` setting is a list of keywords you provide. So you could do
```
%set user_graph_keywords graph_keyword1,graph_keyword2 --permanently 
```

**Comment by alanzchen** [comment]
Oh sorry, I didn't read the docs carefully. `graph display` will do the trick.

But one quick follow up problem here. It seems that `stata_kernel` will display the previous graph that did not get exported (like `vioplot` before this fix) after a failed attempt to create a graph in following cells.

Like this:

<img width="713" alt="screen shot 2018-10-05 at 11 11 24 am" src="https://user-images.githubusercontent.com/2144783/46546843-e3a63800-c88f-11e8-9b84-9b8a41c3af0c.png">

**Comment by kylebarron** [comment]
If it wasn't clear, you need to upgrade:
```
pip install stata_kernel --upgrade
```

**Comment by alanzchen** [comment]
Yes, that is an extension called `ExecuteTime`.

**Comment by alanzchen** [comment]
@kylebarron Maybe I should clarify the new problem that I mentioned.

> I know this problem will not happen in the first place after this fix. But if the user forgets to set up the list properly, it is possible for the inline graphs to be messed up. It would be dangerous.

 So imagine this: suppose there is a custom command called `example_graph` that produces a graph. The user forgets to include `example_graph` in the list. So the users do the following:

1. `example_graph` // Executed successfully but the graph is not showing up.
2. `scatter a b c` // Failed to execute because of a variable is missing. But `stata_kernel` shows the graph that is produced in (1) by quietly appending `graph export`.

As a result, the output of the notebook will be very confusing.

Maybe it would be better to not append `graph export` if the cell is returned with an error?

**Comment by kylebarron** [comment]
That's #157.  Should be an easy fix, just haven't gotten around to it.

**Comment by alanzchen** [comment]
Thanks. I wasn't aware that it is already been noticed.

**Comment by jhconning** [comment]
Minor observation:   the list of graph keywords must not include any spaces between keywords to work:

For example, this will fail:

```
%set user_graph_keywords vioplot, coefplot, rdplot --permanently 

  error: unrecognized arguments: coefplot, rdplot
  usage: %set [-h] [--permanently] [--reset] key value
```

Removing those spaces fixes the problem:

```
%set user_graph_keywords vioplot,coefplot,rdplot --permanently 
```

This could be confusing to users not only because many people like to add a space after a comma to make code more readable but also because the default `.stata_kernel.conf` file (also quoted in [the graph settings documentation](https://kylebarron.github.io/stata_kernel/using_stata_kernel/configuration/#graph-settings) ) has spaces between keywords.  The defaults in the .conf file are listed as:

```
user_graph_keywords = vioplot, coefplot
```

No big deal, but thought I'd mention it in case others stumbled on the same thing.

**Comment by kylebarron** [comment]
I updated the docs to reflect that. Thanks.
