### ISSUE TITLE
Stata 14 support

### ISSUE THREAD

**Issue by TiesdeKok** [kylebarron/stata_kernel#21]
I suspect that the `nomsg` parameter was added with the most recent version Stata (i.e. 15). 

When trying to execute code using Stata 14 I get an error:

![image](https://user-images.githubusercontent.com/13317782/43736562-e6b6770e-9972-11e8-97c5-c8fffdd20c2a.png)

https://github.com/kylebarron/stata_kernel/blob/2d408bcd70188bc8e0d592eff10db948f52f0ff9/stata_kernel/kernel.py#L297

**Comment by kylebarron** [comment]
I didn't realize that wasn't in Stata 14. I'll take that out; I just have to change the log parsing as well then

**Comment by kylebarron** [comment]
Try again and let me know if it works for you.

**Comment by TiesdeKok** [comment]
Thanks! That solved the `nomsg` problem.

Unfortunately I did encounter another problem when trying to show a graph:

![image](https://user-images.githubusercontent.com/13317782/43742978-dc0094d2-9988-11e8-9931-5ed26ccd4eed.png)

Apparantly the SVG option is new to Stata 15. This is rather unfortunate as it also affects the console version on Unix systems. When I start up a Stata kernel on Linux and try to show a graph I get the same error. 

For Windows (and MacOS?) you can probably use a PNG instead, but for Linux this is not possible. My work-around for iPystata (i.e. using PDFs) is certainly not ideal but that was the best solution that I could find.

**Comment by kylebarron** [comment]
I think Stata 14 can export to SVG [(source)](http://repec.sowi.unibe.ch/stata/webdoc/graphs.html#h-2). I was able to export a graph to SVG on Stata 14.2 on a Unix server.

It's possible that Stata couldn't export to SVG on Windows in 14. I can add PNG or PDF as a backup soon. Also, try again because I made some fixes in the last few hours.
