### ISSUE TITLE
Linesize issues

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#216]
@mcaceresb 	Do you know how the linesize could change within an `if` block? In the `if` block the linesize appears to be 79 (you can see the `>` line continuations). But after the `if` block, ``di `c(linesize)'`` says 255...
```
. if _rc == 0 {
.     noi gr export /Users/lstein2/.stata_kernel_cache/graph$stata_kernel_graph
> _counter.svg, width(600) replace
(file /Users/lstein2/.stata_kernel_cache/graph0.svg written in SVG format)
.     noi gr export /Users/lstein2/.stata_kernel_cache/graph$stata_kernel_graph
> _counter.pdf, replace
(file /Users/lstein2/.stata_kernel_cache/graph0.pdf written in PDF format)
.     global stata_kernel_graph_counter = $stata_kernel_graph_counter + 1
.     graph close
. }            
 
. `43bc29aead94b3b319edc5e3d222e946'
. di `c(linesize)'
`83b14c3154752dfbf1b0322b89ffcf55'
di `c(linesize)'
255
```

**Comment by mcaceresb** [comment]
That's really strange. Not sure why the if block changes it...

**Comment by kylebarron** [comment]
Yeah I have no idea either. The guy says (and you can tell from the log if you look closely) that if he runs just
```
scatter mpg weight
```
by itself, the output wraps like the above and the extra code lines aren't hidden correctly.

But if he runs all of the following together:
```
sysuse auto
count
descr
scatter mpg weight
```
then it works! Crazy... (this is around line 400)

**Comment by mcaceresb** [comment]
Have you been able to reproduce this?

**Comment by kylebarron** [comment]
No, not on my own machine. He's using Mac and Stata 15.1

**Comment by kylebarron** [comment]
I'm also on Mac and using Stata 15.1, also Special Edition

**Comment by mcaceresb** [comment]
I know Stata re-sets linesize automagically when you resize the console or GUI...but I'm pretty sure that stops if linesize is set manually, and there is no reason why the console should get "resized" during an if statement.

**Comment by kylebarron** [comment]
And it's pretty reproducible as well. Several times in the log file it shows up the same.

**Comment by kylebarron** [comment]
I asked him to try https://github.com/kylebarron/stata_kernel/tree/linewrapping-bandaid, which moves the if block into several single-line if statements. No idea if that would fix anything, but worth a try.

**Comment by kylebarron** [comment]
Also, [Fernando Perez](https://twitter.com/fperez_org) (creator of IPython/Jupyter) [retweeted](https://twitter.com/kylebarron2/status/1055130936482951168) the existence of the Stata kernel, so maybe it'll get more traction today?

**Comment by kylebarron** [comment]
Yeah! I'm just hoping not all mac users are having these issues...

**Comment by kylebarron** [comment]
I only just added the specific offending code today in https://github.com/kylebarron/stata_kernel/pull/210

**Comment by mcaceresb** [comment]
Why if instead of cap to gr export?

**Comment by kylebarron** [comment]
The specific reason for that is explained here: https://github.com/kylebarron/stata_kernel/issues/197#issuecomment-427467653. It's not necessarily incredibly important that it be fixed, but I just expected it to work fine...

**Comment by mcaceresb** [comment]
Does it actually cause stuff to fail or is it that the log temporarily falls out of sync?

**Comment by kylebarron** [comment]
Latter

**Comment by mcaceresb** [comment]
> The specific reason for that is explained here

Commands not prepended by cap do not change `_rc` ... Ah, but this is wrapped up in include, right?

**Comment by kylebarron** [comment]
Specifically the graph temporarily falls out of sync. Basically the previous graph window still exists and a new one isn't created

**Comment by mcaceresb** [comment]
If I recall, single lines are not wrapped up include, so in that case this would still fall out of sync, right?

**Comment by kylebarron** [comment]
Oh yeah.. you're right

**Comment by kylebarron** [comment]
I momentarily forgot about when I sent with include vs not

**Comment by kylebarron** [comment]
I suppose I'll revert to just using `cap noi gr export`

**Comment by mcaceresb** [comment]
Doesn't that re-introduce the problem that user pointed out?

I thought the way to deal with this was to look for an error code in the program and run the plot exporting whenever there were no errors at all. It definitely worked like that at some point, can't quite remember why it changed.

**Comment by kylebarron** [comment]
> Doesn't that re-introduce the problem that user pointed out?

Yes it does, but I think that problem is pretty rare. And I have no idea how rare this new issue is. (I just had a friend with access to a mac also try it and fail to reproduce the issue.)

Currently, the program automatically adds `graph export` after every graph command. Until 1.6.0, if the graph command failed, i.e. `scatter asdf sdflk`, you'd see something like "can't export graph, no graph window".

Also, I realize I never shared screenshots:
![image](https://user-images.githubusercontent.com/15164633/47468543-db278a00-d7c9-11e8-922b-f54290709d21.png)
that's what the person is seeing.

**Comment by lukestein** [comment]
Hi. I'm "the guy" 😏

Tried to upgrade to the linewrapping-bandaid version per Twitter DM from @kylebarron but got an xcrun error. I'm guessing this may be because I don't have xcode installed (including command line tools.) I can try to install what I need if I get directions. To be clear my goal is to be helpful to the project, but I am limited in tech sophistication and don't mean to pull attention away from other things.

![image](https://user-images.githubusercontent.com/44452336/47469221-9c3b0980-d7b4-11e8-98cc-95d5715f06ee.png)

**Comment by kylebarron** [comment]
That just means you don't have git installed. The Git homepage says "The easiest is probably to install the Xcode Command Line Tools", so just do that. (Apparently, it says that if you type `git` into the terminal, it'll prompt you to install it automatically?)

**Comment by lukestein** [comment]
OK. Also, I had a short expiration set on the log pastebin and since it was an anon post I couldn't extend it. Log from ~/.stata_kernel_cache/console_debug.log
is reposted here:
https://pastebin.com/jq84Uuw5

**Comment by kylebarron** [comment]
@lukestein 	Are you able to install xcode command line tools? If typing `git` doesn't work, this should:
```
xcode-select --install
```

**Comment by lukestein** [comment]
Typicing `git` didn't help, but installed Xcode Command Line Tools using `xcode-select --install`.

Ran (successfully I think) this upgrade:
`pip install git+https://github.com/kylebarron/stata_kernel@linewrapping-bandaid --upgrade'
![image](https://user-images.githubusercontent.com/44452336/47471716-7c114780-d7c0-11e8-9b1c-09cb9846e13a.png)


Unfortunately, I have the same problem as before. Running as individual commands, I get this
![image](https://user-images.githubusercontent.com/44452336/47471739-99deac80-d7c0-11e8-8d0e-fdde1387d8aa.png)

Running using "Run all," I get a nasty error
![image](https://user-images.githubusercontent.com/44452336/47471766-b2e75d80-d7c0-11e8-8748-e7553a3da2e3.png)

Log file is here:
https://pastebin.com/KtbZbG79

**Comment by kylebarron** [comment]
I can't understand what Stata's doing... lines 295-311

It's line wrapping at 79 characters, but then when I ask for the linesize it says 255??
```
. cap noi gr export /Users/lstein2/.stata_kernel_cache/graph$stata_kernel_graph
> _counter.svg, width(600) replace
(file /Users/lstein2/.stata_kernel_cache/graph0.svg written in SVG format)
 
. cap noi gr export /Users/lstein2/.stata_kernel_cache/graph$stata_kernel_graph
> _counter.pdf, replace
(file /Users/lstein2/.stata_kernel_cache/graph0.pdf written in PDF format)
 
. global stata_kernel_graph_counter = $stata_kernel_graph_counter + 1
 
. cap graph close            
 
. `48b322849105f74482050b0ef593e274'
. di `c(linesize)'
`83b14c3154752dfbf1b0322b89ffcf55'
di `c(linesize)'
255
```

**Comment by kylebarron** [comment]
Let me try this again on my mac with Python 3.7. I've been using Python 3.6

**Comment by kylebarron** [comment]
Even with Python 3.7, I can reproduce neither problem.

**Comment by kylebarron** [comment]
@lukestein 	Can you try what @mcaceresb 	suggested above?

**Comment by lukestein** [comment]
> If you run
> 
> ```stata
> set linesize 40
> scatter mpg weight
> 
> set linesize 255
> scatter mpg weight
> ```
> 
> what happens?

Error in the first case, works in the second case:
![image](https://user-images.githubusercontent.com/44452336/47472914-3efb8400-d7c5-11e8-80a0-c55cf26dd985.png)

**Comment by kylebarron** [comment]
@lukestein 	

We expect the error in the first case. 

Can you try again in the second case where you run each line separately? That actually gets run slightly differently by the package than when you select two lines.

The second case is what we expect to work all along. When starting Stata initially, we send `set linesize 255` (which means that Stata will create a line break after every 255 characters on a single logical line).

**Comment by lukestein** [comment]
Run separately, it gives an error for linesize either too short or too long, though the error is different. Too short and it doesn't render any graph
![image](https://user-images.githubusercontent.com/44452336/47473461-8420b580-d7c7-11e8-9ca5-af8b812bc983.png)


Too long and it renders the graph with the extra code before and after
![image](https://user-images.githubusercontent.com/44452336/47473480-a31f4780-d7c7-11e8-9601-be6cfe216aee.png)

**Comment by lukestein** [comment]
The move from 74 to 75 is important:
![image](https://user-images.githubusercontent.com/44452336/47473534-dcf04e00-d7c7-11e8-99da-88a01eeef571.png)

As is the move from 82 to 83:
![image](https://user-images.githubusercontent.com/44452336/47473606-23de4380-d7c8-11e8-9dbd-3b9575017f2e.png)

**Comment by kylebarron** [comment]
Wow. That's crazy. @mcaceresb 	any ideas?

@lukestein 	Can you try changing the setting so that you're using the "automation" backend instead of the "console" backend. I think you should be able to do 
```
%set execution_mode automation --permanently
```
and restart. Otherwise just edit the text file at `~/.stata_kernel.conf`. I'm hoping that that might work better.

**Comment by kylebarron** [comment]
Pretty much the last thing I can think of right now... Can you try again with another test?
```
pip install git+https://github.com/kylebarron/stata_kernel@dev-issue-216 --upgrade
```

**Comment by kylebarron** [comment]
I tested out the automation mode again, and it was slow for me too. I'm not quite sure why that is. It seemed as if the output in the Stata terminal was moving slowly, and that's the limiting factor.

**Comment by lukestein** [comment]
Ran that `pip install` successfully. Had the same result in automation mode: No bugs running line-by-line, (though slow), nasty red exception if I `Hydrogen > Run All`.

Then switched back to console mode. Same errors as before ☹️
![image](https://user-images.githubusercontent.com/44452336/47475757-db2b8800-d7d1-11e8-8b2f-f4f271a602de.png)

I'm done for the night. Thanks for all your work on this awesome project.

**Comment by kylebarron** [comment]
Sorry, I have no idea how to fix this, at least without fixing the difficult, general problem that is https://github.com/kylebarron/stata_kernel/issues/151
