### ISSUE TITLE
Add coefplot as default graph keyword

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#221]

**Comment by mcaceresb** [comment]
In  general it might be nice to allow the user to add plot keywords. For instance

```
%set graph_keywords coefplot myPrettyPlot
```

The default behavior would be to append. Maybe also allow replace and delete?

**Comment by kylebarron** [comment]
```
%set user_graph_keywords coefplot, myprettyplot
```
Should already work I think

**Comment by mcaceresb** [comment]
Very cool. I was looking under "g". Should have grepped the repo instead.

**Comment by mcaceresb** [comment]
Sorry. I was able to add but not reset? It seems both key and value are always required but line 440 of `stata_magics.py` says I can't set values with reset. Should I open a new issue or am I just doing something daft?

![screenshot_20181101_185943](https://user-images.githubusercontent.com/4219197/47884747-5f03f680-de08-11e8-93ba-92f6536c458b.png)

**Comment by kylebarron** [comment]
I haven't checked `reset` in a while.
