### ISSUE TITLE
Support no user conf file and/or support site-wide conf file

### ISSUE THREAD

**Issue by ryanlovett** [kylebarron/stata_kernel#222]
**Is your feature request related to a problem? Please describe.**
I installed stata_kernel in a JupyterHub environment using `python -m stata_kernel.install --sys-prefix`. This makes the kernel available for everyone but there is no site-wide stata_kernel.conf. The kernel will error unless every user runs `python -m stata_kernel.install` on their own.

**Describe the solution you'd like**
stata_kernel would not require a configuration file. It would use safe defaults, e.g. wouldn't require an explicit path to stata and assumes the Jupyter notebook process can find stata or stata-mp in PATH.

**Describe alternatives you've considered**
stata_kernel could check for, and use, a site-wide configuration file whose values are overridden by a user's own, if it exists. This is installed when --sys-prefix is passed to install. 

**Additional context**
N/A

**Comment by kylebarron** [comment]
Thanks for the issue. I hadn't considered the details of JupyterHub or system-wide Jupyter Notebook installations.

> stata_kernel would not require a configuration file

That's possible. I'd have to raise an error if Stata is not on the PATH. There are already backup defaults for most of the times I'm retrieving a setting, so I don't think I'd have to change too much.

I also think there are benefits to allowing a system-level configuration file, say if the sysadmin wanted to set a default `cache_directory` for each user or something.

Note to self:
Move `find_path()` from `install_conf()` to its own function within `config.py` that `install.py` can access.

**Comment by ryanlovett** [comment]
@kylebarron Awesome, thanks! I'll try it out tomorrow afternoon and report back.

**Comment by ryanlovett** [comment]
This worked great. I did not run `python -m stata_kernel.install`, either as the notebook user or as an admin and I deleted the notebook user's stata kernel config beforehand.

**Comment by kylebarron** [comment]
> I did not run `python -m stata_kernel.install`

Had you run that once previously? Without that step the install _shouldn't_ work correctly. That's the step in which the Jupyter kernelspec is installed.

So if you do
```
jupyter kernelspec list
```
you should see `stata` listed. If you do 
```
jupyter kernelspec uninstall stata
pip uninstall stata_kernel
rm ~/.stata_kernel.conf
pip install git+https://github.com/kylebarron/stata_kernel@no-conf
```
That will recreate the state after installing from pip but before running `python -m stata_kernel.install`. I don't think that would function correctly?

**Comment by kylebarron** [comment]
Note to self: add `ConfigError` for errors that occur because of insufficient information. Like not knowing a Stata path.

**Comment by kylebarron** [comment]
@ryanlovett 	Sorry I've been dragging my feet a little on this. I'll try to publish a new release for this tonight or tomrrow.

I see Berkeley has department-wide JupyterHub installations for the Stats and Econ departments? That's really impressive.
https://data.berkeley.edu/education/jupyterhub-ecosystem

**Comment by ryanlovett** [comment]
@kylebarron There's definitely no rush since I'm using your no-conf branch. Thanks for taking care of that so quickly.

Re: hubs -- yeah, they're small, but people seem naturally inclined to want to use Jupyter for things so running Hub on Stat and Econ clusters makes sense. The Econ folks use stata quite a bit.

**Comment by Hemken** [comment]
> 
> 
> Yeah. So I think a sysadmin trying to install this for multiple users has to do
> 
> ```
> pip install stata_kernel
> python -m stata_kernel.install --sys-prefix
> ```
> 
> I should add that to the docs when this is merged.

I tried the --sys-prefix flag, and it mostly worked.  But I seem to have lost the ability to run Stata graphs?  Related?
