### ISSUE TITLE
`Help` hangs within mata

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#231]
@mcaceresb 	

type `mata`, enter, then type `help`.

**Comment by mcaceresb** [comment]
Why is [this line](https://github.com/kylebarron/stata_kernel/blob/master/stata_kernel/stata_session.py#L332) `expect_exact`? It's partly what's messing this up. I just want to make sure I'm not breaking sth else.

**Comment by mcaceresb** [comment]
It's an easy fix if I can replace that with `expect`, but I'm not sure if I can. Let me know.

**Comment by kylebarron** [comment]
I believe that `expect_exact` is just a faster version of `expect` because the former uses string comparison (i.e. `in`) and the latter uses regex. So I think it should be fine to change to `expect`.

**Comment by kylebarron** [comment]
Oops. Meant to write that on the tests issue
