### ISSUE TITLE
Highlight syntax is not working in Jupyter Notebook but works when exported as HTML. 

### ISSUE THREAD

**Issue by mr-avila** [kylebarron/stata_kernel#233]
#### Problem description

Highlight syntax is not working in Jupyter Notebook but works when exported as HTML. 

#### Debugging log

[console_debug.log](https://github.com/kylebarron/stata_kernel/files/2561948/console_debug.log)

#### Code Sample (from interactive session)

![image](https://user-images.githubusercontent.com/31955632/48202191-78ef8d00-e364-11e8-8521-e3ea89ca55e5.png)

#### Expected Output (from exported html)

![image](https://user-images.githubusercontent.com/31955632/48202237-9cb2d300-e364-11e8-9295-d5a1e73dbf56.png)

#### Other information

- Operating System: Linux Manjaro with GNOME 
- Stata version: 14.2
- Package Version: 1.6.2
- I did read [the issue 4](https://github.com/kylebarron/stata_kernel/issues/4), but couldn't understand much.
- The highlighting works fine with ATOM + Hydrogen + language-stata (1.7.0) 
- Thank you VERY MUCH for keeping me away from default stata editor!!!

**Comment by mr-avila** [comment]
brilliant! works great!!! In my case, I had to use `sudo mkdir stata` and `sudo wget https://raw.githubusercontent.com/kylebarron/stata_kernel/master/stata_kernel/codemirror/stata.js`) due to permissions in my location folder, which was `/usr/lib/python3.7/site-packages`). 

thank you very much for the great work and support!

**Comment by kylebarron** [comment]
Yeah, that's also why syntax highlighting wasn't automatic. Because Stata kernel couldn't copy a file to that location without elevated permissions

**Comment by alanzchen** [comment]
I am not getting syntax highlighting in Jupyter Lab. Any idea where to put the .js file?

**Comment by kylebarron** [comment]
It doesn't look possible to add the `.js` file anywhere in Jupyter lab after installation. Might be good to follow this issue: https://github.com/jupyterlab/jupyterlab/issues/5504
