### ISSUE TITLE
Data type issues when browsing data

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#237]
To display data with `%head` or `%browse`, I save selected Stata data to a CSV, then load it into Python and display it with Pandas' `DataFrame.to_html()`.

The issue is that I currently use automatic type inference for loading the CSV, so a column of strings that represent numbers will be loaded into Python as numbers.

```stata
clear
set obs 1
gen test = "00100"
%head
```

Will show `100` as a number, not `"00100"` as a string:
![image](https://user-images.githubusercontent.com/15164633/48728843-1e77eb80-ec04-11e8-83ac-790e2958aeda.png)

To fix this, write out a schema of the dtypes of the data to use when loading into Pandas.

**Comment by mcaceresb** [comment]
`pd.read_stata` instead? It's a small dataset anyway.
