### ISSUE TITLE
Problem installing: pygments._mata_builtins

### ISSUE THREAD

**Issue by fishix10** [kylebarron/stata_kernel#238]
Hi. I'm using Anaconda in Windows 10. I installed the package using `pip install stata_kernel` which went fine. I then tried `python -m stata_kernel.install` and get the following error:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "C:\ProgramData\Anaconda3\lib\runpy.py", line 109, in _get_module_details
        __import__(pkg_name)
      File "C:\ProgramData\Anaconda3\lib\site-packages\stata_kernel\__init__.py", line 5, in <module>
        from .kernel import StataKernel
      File "C:\ProgramData\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 17, in <module>
        from .completions import CompletionsManager
      File "C:\ProgramData\Anaconda3\lib\site-packages\stata_kernel\completions.py", line 6, in <module>
        from .pygments._mata_builtins import mata_builtins
    ModuleNotFoundError: No module named 'stata_kernel.pygments._mata_builtins'

I'm not sure what other info would be useful. Please let me know. Any help would be great. Thanks a lot!

PS. Here's my `pip list`

    Package                            Version
    ---------------------------------- ----------
    alabaster                          0.7.12
    anaconda-client                    1.7.2
    anaconda-navigator                 1.9.2
    anaconda-project                   0.8.2
    asn1crypto                         0.24.0
    astroid                            2.0.4
    astropy                            3.0.5
    atomicwrites                       1.2.1
    attrs                              18.2.0
    Babel                              2.6.0
    backcall                           0.1.0
    backports.os                       0.1.1
    backports.shutil-get-terminal-size 1.0.0
    basemap                            1.2.0
    beautifulsoup4                     4.6.3
    bitarray                           0.8.3
    blaze                              0.10.1
    bleach                             3.0.2
    bokeh                              1.0.1
    boto                               2.49.0
    Bottleneck                         1.2.1
    certifi                            2018.10.15
    cffi                               1.11.5
    chardet                            3.0.4
    Click                              7.0
    cloudpickle                        0.6.1
    clyent                             1.2.2
    colorama                           0.4.0
    comtypes                           1.1.7
    conda                              4.5.11
    contextlib2                        0.5.5
    cryptography                       2.3.1
    cycler                             0.10.0
    Cython                             0.29
    cytoolz                            0.9.0.1
    dask                               0.20.2
    datashape                          0.5.4
    decorator                          4.3.0
    defusedxml                         0.5.0
    distributed                        1.24.2
    docutils                           0.14
    entrypoints                        0.2.3
    et-xmlfile                         1.0.1
    fastcache                          1.0.2
    Flask                              1.0.2
    Flask-Cors                         3.0.7
    gevent                             1.3.7
    greenlet                           0.4.15
    h5py                               2.7.0
    heapdict                           1.0.0
    html5lib                           1.0.1
    idna                               2.7
    imageio                            2.4.1
    imagesize                          1.1.0
    importlib-metadata                 0.6
    ipykernel                          5.1.0
    ipython                            7.1.1
    ipython-genutils                   0.2.0
    ipywidgets                         7.4.2
    isort                              4.3.4
    itsdangerous                       1.1.0
    jdcal                              1.4
    jedi                               0.13.1
    Jinja2                             2.10
    jsonschema                         2.6.0
    jupyter                            1.0.0
    jupyter-client                     5.2.3
    jupyter-console                    6.0.0
    jupyter-core                       4.4.0
    kiwisolver                         1.0.1
    lazy-object-proxy                  1.3.1
    llvmlite                           0.25.0
    locket                             0.2.0
    lxml                               4.2.5
    MarkupSafe                         1.1.0
    matplotlib                         3.0.2
    mccabe                             0.6.1
    menuinst                           1.4.14
    mistune                            0.8.4
    mkl-fft                            1.0.6
    mkl-random                         1.0.1
    more-itertools                     4.3.0
    mpmath                             1.0.0
    msgpack                            0.5.6
    multipledispatch                   0.6.0
    navigator-updater                  0.2.1
    nbconvert                          5.4.0
    nbformat                           4.4.0
    networkx                           2.2
    nltk                               3.3
    nose                               1.3.7
    notebook                           5.7.2
    numba                              0.40.0
    numexpr                            2.6.8
    numpy                              1.15.4
    odo                                0.5.1
    olefile                            0.46
    openpyxl                           2.5.9
    packaging                          18.0
    pandas                             0.23.4
    pandocfilters                      1.4.2
    parso                              0.3.1
    partd                              0.3.9
    path.py                            11.5.0
    pathlib2                           2.3.2
    patsy                              0.5.1
    pep8                               1.7.1
    pexpect                            4.6.0
    pickleshare                        0.7.5
    Pillow                             5.3.0
    pip                                18.1
    pluggy                             0.8.0
    ply                                3.11
    prometheus-client                  0.4.2
    prompt-toolkit                     2.0.7
    psutil                             5.4.8
    ptyprocess                         0.6.0
    py                                 1.7.0
    pycosat                            0.6.3
    pycparser                          2.19
    pycrypto                           2.6.1
    pycurl                             7.43.0.2
    pyflakes                           2.0.0
    Pygments                           2.2.0
    pylint                             2.1.1
    pyodbc                             4.0.24
    pyOpenSSL                          18.0.0
    pyparsing                          2.3.0
    pyproj                             1.9.5.1
    pyshp                              1.2.12
    PySocks                            1.6.8
    pytest                             4.0.0
    pytest-arraydiff                   0.2
    pytest-astropy                     0.4.0
    pytest-doctestplus                 0.2.0
    pytest-openfiles                   0.3.0
    pytest-remotedata                  0.3.1
    python-dateutil                    2.7.5
    pytz                               2018.7
    PyWavelets                         1.0.1
    pywin32                            224
    pywinpty                           0.5.4
    PyYAML                             3.13
    pyzmq                              17.1.2
    QtAwesome                          0.5.3
    qtconsole                          4.4.3
    QtPy                               1.5.2
    requests                           2.20.1
    rope                               0.11.0
    ruamel-yaml                        0.15.46
    scikit-image                       0.14.0
    scikit-learn                       0.20.0
    scipy                              1.1.0
    seaborn                            0.9.0
    selenium                           3.13.0
    Send2Trash                         1.5.0
    setuptools                         40.6.2
    simplegeneric                      0.8.1
    singledispatch                     3.4.0.3
    six                                1.11.0
    snowballstemmer                    1.2.1
    sortedcollections                  1.0.1
    sortedcontainers                   2.0.5
    SQLAlchemy                         1.2.14
    stata-kernel                       1.7.1
    statsmodels                        0.9.0
    sympy                              1.3
    tables                             3.2.2
    tblib                              1.3.2
    terminado                          0.8.1
    testpath                           0.4.2
    toolz                              0.9.0
    tornado                            5.1.1
    traitlets                          4.3.2
    typed-ast                          1.1.0
    unicodecsv                         0.14.1
    urllib3                            1.24.1
    wcwidth                            0.1.7
    webencodings                       0.5.1
    Werkzeug                           0.14.1
    wheel                              0.32.3
    widgetsnbextension                 3.4.2
    win-inet-pton                      1.0.1
    win-unicode-console                0.5
    wincertstore                       0.2
    wrapt                              1.10.11
    xlrd                               1.1.0
    XlsxWriter                         1.1.2
    xlwings                            0.14.1
    xlwt                               1.3.0
    zict                               0.1.3

**Comment by kylebarron** [comment]
Thanks for reporting. We just forgot to list a file as necessary to include.

I just pushed a new release, so you should be able to install fine now.
