### ISSUE TITLE
Kernel Busy

### ISSUE THREAD

**Issue by fishix10** [kylebarron/stata_kernel#240]
Using version 1.7.2 which resolved issue #238. Now I got the kernel started.
I get the "Kernel Ready" then "Kernel Idle" on top right.
When I type in a command and `Ctrl + Enter`,  it displays the expected result (like `di "Hello"`), but the kernel doesn't return to idle. Thanks a lot!

I've also attached the log file here.
[log7.log](https://github.com/kylebarron/stata_kernel/files/2600077/log7.log)

Also, this is what appears in Jupyter Notebook (different run, but similar message):

    [I 21:23:46.020 NotebookApp] Accepting one-time-token-authenticated connection from ::1
    [I 21:23:49.483 NotebookApp] Creating new notebook in
    [I 21:23:50.327 NotebookApp] Kernel started: 2d098fa0-3d20-4755-84c6-96014f13760a
    [I 21:23:53.900 NotebookApp] Adapting to protocol v5.1 for kernel 2d098fa0-3d20-4755-84c6-96014f13760a

**Comment by kylebarron** [comment]
Sorry about that. I pushed another release to PyPI and this time I actually tested it on Windows.

**Comment by fishix10** [comment]
Thank you so much @mcaceresb @kylebarron for all your help! Saved me from actually typing up a LaTeX doc for my class :P
