### ISSUE TITLE
Open full Stata session from stata_kernel?

### ISSUE THREAD

**Issue by fishix10** [kylebarron/stata_kernel#243]
If I type in `browse`, then the original Stata browse page pops up. I'm just wondering if, analogously, is there a way to call up the full Stata interface from stata_kernel (and not just the browse window).

**Comment by kylebarron** [comment]
On Windows, the full Stata interface exists but is hidden. The idea is that if you're using Jupyter, it's clutter to also show the Stata window

**Comment by kylebarron** [comment]
@fishix10 	as of the latest version you can use `%show_gui` and `%hide_gui`
