### ISSUE TITLE
Displaying images no longer works in qtconsole

### ISSUE THREAD

**Issue by mcaceresb** [kylebarron/stata_kernel#245]
#### Problem description

Merge request #235 (in an attempt to fix #234) broke image display in `qtconsole`. I don't think there is a universal fix. Perhaps an option to wrap SVG in an iframe? The double display thing would not really a problem in qtconsole bc not everything is wrapped up in HTML.

#### Debugging log

Everything is working as designed, but qtconsole can't display HTML.

#### Code Sample

```stata
sysuse auto
hist price
```

#### Expected Output

A plot displayed.

#### Other information

- Linux
- Stata version 15.1
- Package version 1.7.4

**Comment by kylebarron** [comment]
Sorry just got back from beautiful southern Utah :)

The iframe enclosed svg is still sent as mimetype svg+xml right? I'd try sending that as text/html and the pure svg at the same time

**Comment by kylebarron** [comment]
Oh, I didn't realize the iframe enclosed svg was changed to be sent with `text/html`. Yes, I think sending both should fix. You're welcome to make a PR.
