### ISSUE TITLE
sos-stata is released to support Stata through stata_kernel.

### ISSUE THREAD

**Issue by BoPeng** [kylebarron/stata_kernel#255]
@kylebarron Not sure if this is the best way to contact you but I am writing to let you know that I have added the [sos-stata](https://github.com/vatlab/sos-stata) language module to support the use of Stata with other kernels in one Jupyter notebook through `stata_kernel`. Please see the [sos documentation on Stata](https://vatlab.github.io/sos-docs/doc/documentation/Supported_Languages.html#Stata--19) if you are interested.

Right now sos only allows the exchange of "current dataset" with Stata because I do not know how "variables" work in Stata. It also only reports `version` as `%sessioninfo` because I do not know if there are other session-related information to report (e.g. version of Stata libraries). Anyway, the module seems to work all right and please feel free to let me know if you have any comment.

**Comment by kylebarron** [comment]
If you create an issue on sos-stata and use @kylebarron 	, I'll still be notified about it.

"Variables" in stata are just macros. You can't have more than a single dataset. There really isn't as much emphasis on libraries in the Stata community.

**Comment by BoPeng** [comment]
So I guess what I have in `sos-stata` would be good enough for this language then.

I did read something like
```
mata
x = 4
end
```
and `x` is even persistent, but I do not know if this `x` can be used outside of `mata`. If it can, it makes some sense to pass `x` from outside to `Stata`.

**Comment by mcaceresb** [comment]
Mata objects are persistent in general. You can print via

```
mata x
```

To pass them to Stata, you would use one of the `st_*` functions or the `getmata` built-in program.

**Comment by BoPeng** [comment]
I tried to understand examples [here](https://stats.idre.ucla.edu/stata/code/a-code-fragment-for-combining-a-histogram-and-boxplot-in-one-graph/) but could not guess what is this `gen pmin=r(min)` thing. I certainly do not have time to learn Stata in full so I will just stop here. Please create a ticket even a PR if you find it useful to pass variables in and out of Stata in a SoS notebook.
