### ISSUE TITLE
Converting Stata magic back to Stata code

### ISSUE THREAD

**Issue by lordflaron** [kylebarron/stata_kernel#259]
Hi,

Thank you for this awesome Stata kernel! I'm co-hosting a workshop soon on transparency and reproducibility to a class  mostly Stata users and your kernel has opened up the whole Jupyter ecosystem for them. 

I'm currently working on writing a custom exporter that converts the Jupyter notebook back to a dofile and I'm struggling with how to convert your Stats magics back to code that Stata might understand. Is there a way to do this from the kernel itself (I'm thinking it might be useful in case you end up adding new magics in the future), or would it be easier just to do it manually (parsing the code and doing if statements)?

**Comment by kylebarron** [comment]
> writing a custom exporter

You can export directly from Jupyter notebooks to Stata files. Choose "export Notebook to executable script"
![image](https://user-images.githubusercontent.com/15164633/49761146-30452f80-fc94-11e8-9dcb-f96dfe481fcd.png)

**Comment by kylebarron** [comment]
For the most part, the magics have no comparable Stata command. There's really no way to tell if your code is running through Jupyter or not. If statements won't work because the magic has to be the first text sent to the kernel.

I agree that it's not ideal, but I decided to model it after Python.

**Comment by lordflaron** [comment]
Thank you for that! But as it stands now, in the test document that I wrote, it only exports the code itself, and none of the markdown cells, nor does it convert the magics. I suppose converting the magics isn't vital as it's mostly for exploring the data from within the notebook.

Also, does this export feature only work from with JupyterLab? 

> For the most part, the magics have no comparable Stata command. There's really no way to tell if your code is running through Jupyter or not. If statements won't work because the magic has to be the first text sent to the kernel.

Thanks for letting me know about that. In any case, perhaps it would be worthwhile for it to export with markdown cells, not just the code.

In any case, thanks so much for the work and the help!

**Comment by lordflaron** [comment]
Sorry, accidental close

**Comment by kylebarron** [comment]
The export feature also works from Jupyter Notebook. I don't have control over what it exports because that isn't code provided by the kernel. It's provided by [nbconvert](https://github.com/jupyter/nbconvert).

If you want a quick and dirty conversion script that converts the markdown sections too, you can use something simple like this:
```py
import json

def main():

    input_file = '/home/kyle/Untitled2.ipynb'
    output_file = 'output.do'

    with open(input_file) as f:
        ipynb = json.load(f)

    output = []
    comment_symbol = '// '
    for cell in ipynb['cells']:
        if cell['cell_type'] == 'markdown':
            lines = [comment_symbol + line for line in cell['source']]
            output.append('\n' + ''.join(lines) + '\n')
        elif cell['cell_type'] == 'code':
            output.append(''.join(cell['source']))

    output = '\n'.join(output)

    with open(output_file, 'w') as f:
        f.write(output)

if __name__ == '__main__':
    main()
```

**Comment by lordflaron** [comment]
Thanks so much for that script. Unfortunately, the students of the workshop will all probably be social scientists who might be unfamiliar with python or even the command prompt. I've put together a rather simply extension for doing the export here if it's of interest to you.

https://github.com/lordflaron/StataDoExport

**Comment by kylebarron** [comment]
That looks quite nice. 

From the looks of it, it only works with jupyter notebook? Or does it work with jupyter lab too?

I've started recommending jupyter lab first in the documentation, since it's a more modern interface. Eventually the notebook interface will be deprecated but I doubt that will happen anytime soon.

**Comment by lordflaron** [comment]
From what I understand, nbconvert works in both jupyter notebooks and lab. From a cursory glance, I've been able to do so in both the lab and the notebook.

**Comment by kylebarron** [comment]
Nbconvert does work in both, but I was guessing you'd have to create a purpose-built jupyter labextension to get it to work in Jupyter Lab.

**Comment by kylebarron** [comment]
Actually I may end up creating a separate extension to do this for general purposes if I have time.

**Comment by lordflaron** [comment]
Yeah that would be awesome. Let me know if there's something I can do to improve the extension and we can collaborate!

**Comment by kylebarron** [comment]
You may be interested in the upcoming notebook import and export as parts of Hydrogen https://github.com/nteract/hydrogen/pull/1501, https://nteract.gitbooks.io/hydrogen/docs/Usage/NotebookFiles.html

**Comment by kylebarron** [comment]
I'm going to close this for now. There will hopefully be more jupyter notebook support in Atom/Hydrogen in the future
