### ISSUE TITLE
Issue with Install

### ISSUE THREAD

**Issue by joearossetti** [kylebarron/stata_kernel#276]
After installing via Anaconda and running in Atom via Hydrogen I get the following error message:

> Traceback (most recent call last): File "C:\Users\jrossetti\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 183, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "C:\Users\jrossetti\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 142, in _get_module_details return _get_module_details(pkg_main_name, error) File "C:\Users\jrossetti\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 109, in _get_module_details import(pkg_name) File "C:\Users\jrossetti\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel__init__.py", line 5, in from .kernel import StataKernel File "C:\Users\jrossetti\AppData\Local\Continuum\anaconda3\lib\site-packages\stata_kernel\kernel.py", line 8, in from PIL import Image File "C:\Users\jrossetti\AppData\Local\Continuum\anaconda3\lib\site-packages\PIL\Image.py", line 64, in from . import _imaging as core ImportError: DLL load failed: The specified module could not be found.

**Comment by kylebarron** [comment]
I think that usually means that Anaconda didn't install correctly. Could you try uninstalling and reinstalling it?

**Comment by kylebarron** [comment]
The other way that might fix it is to run
```
conda install -c conda-forge pillow
```
and then try again.

**Comment by joearossetti** [comment]
Thanks for the quick responses. I tried uninstalling and reinstalling Anaconda, but I still received the same error message.

I tried the second solution, but I got an error--my guess is that this is because I am not the administrator: 

> ERROR conda.core.link:_execute(507): An error occurred while uninstalling package 'defaults::conda-4.5.12-py37_0'.
> PermissionError(13, 'Access is denied')
> Attempting to roll back.
> 
> Rolling back transaction: done
> 
> PermissionError(13, 'Access is denied')

**Comment by kylebarron** [comment]
If you're on a shared machine where Anaconda is installed system wide, you might need to use a conda environment. Something like
```
conda create -n myenv python3 pillow -c conda-forge
source activate myenv
pip install stata_kernel
```

**Comment by kylebarron** [comment]
You need to open Atom from the terminal after entering the environment
```
source activate myenv
atom .
```

**Comment by joearossetti** [comment]
Running atom from the anaconda prompt seems to have resolved the one issue, however, I now get the following message: 

> Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch IDispatch = pythoncom.connect(IDispatch) pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\ProgramData\Anaconda3\lib\site-packages\stata_kernel__main__.py", line 4, in IPKernelApp.launch_instance(kernel_class=StataKernel) File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance app.initialize(argv) File "", line 2, in initialize File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error return method(app, args, **kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 484, in initialize self.init_kernel() File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel user_ns=self.user_ns, File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance inst = cls(args, **kwargs) File "C:\ProgramData\Anaconda3\lib\site-packages\stata_kernel\kernel.py", line 73, in init self.stata = StataSession(self, self.conf) File "C:\ProgramData\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 97, in init self.init_windows() File "C:\ProgramData\Anaconda3\lib\site-packages\stata_kernel\stata_session.py", line 158, in init_windows self.stata = win32com.client.Dispatch("stata.StataOLEApp") File "C:\ProgramData\Anaconda3\lib\site-packages\win32com\client__init__.py", line 95, in Dispatch dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx) File "C:\ProgramData\Anaconda3\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName return (_GetGoodDispatch(IDispatch, clsctx), userName) File "C:\ProgramData\Anaconda3\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch) pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

**Comment by joearossetti** [comment]
I followed the instructions here: https://www.stata.com/automation/#install for my version of Windows (which is not Vista). I executed the register command both in the command prompt and in my conda environment.

**Comment by kylebarron** [comment]
I've found that you always need to use the Vista instructions, regardless of the OS version.

I'll improve the error message so that it's clear that the type library is the issue.

**Comment by robsunch** [comment]
> You need to open Atom from the terminal after entering the environment
> 
> ```
> source activate myenv
> atom .
> ```

Had the same problem and solved by starting Atom from the Anaconda environment. Thanks.
