### ISSUE TITLE
Wrong _rc

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#288]
#### Problem description

Open Stata through Jupyter

```
cap di "hi"
di _rc
```
Prints `111`. `r(111)` means no variables defined, so there's probably something in the ado files we run that resets the capture value. We should hold the user's `_rc` and then restore it after running the kernel's ado files.

**Comment by kylebarron** [comment]
@mcaceresb 	Do you know of any way to set `_rc`?

I was trying to save it, run commands, and then reset it, but it appears we can't set a scalar with that name...
![image](https://user-images.githubusercontent.com/15164633/52023714-3a352300-24cc-11e9-8100-bd0bc373ee9d.png)

**Comment by kylebarron** [comment]
Oh you can just do `cap exit 1234` to put 1234 into `_rc`

**Comment by mcaceresb** [comment]
You can also do `cap error 1234`

**Comment by kylebarron** [comment]
Thanks; from the Stata help it seems that `cap exit` and `cap error` would do the same thing
