### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by vernongayle** [kylebarron/stata_kernel#289]
#### Problem description

Dear Kyle - we have been running your most excellent Stata kernel.

I have just had a new machine delivered and I can't get the kernel to work.

(base) C:\Users\vgayle>pip install stata-kernel
Collecting stata-kernel
  Using cached https://files.pythonhosted.org/packages/67/86/5979c2b683851f9e6a0a672ceaee3171fe7e18e152554deb0d62101c9879/stata_kernel-1.10.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\vgayle\appdata\local\temp\pip-install-oaoizl\stata-kernel\setup.py", line 2, in <module>
        from subprocess import run
    ImportError: cannot import name run

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\vgayle\appdata\local\temp\pip-install-oaoizl\stata-kernel\

I am running window 10 and Stata 15 SE  64 .

Many thanks in advance for your inputs.
Vernon

**Comment by kylebarron** [comment]
This means that you're trying to run on an older version of Python. Stata kernel requires Python 3.5 or newer (It won't work with anything Python 2.x). You can run `python --version` from the command line to see what version of Python you have installed.

**Comment by kylebarron** [comment]
In the future it should be clearer that you've accidentally installed using Python 2:
https://github.com/kylebarron/stata_kernel/commit/744fc130084ba335e2e2fc8c6ca96630b44c201e
