### ISSUE TITLE
Failing examples for removing comments

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#29]
![image](https://user-images.githubusercontent.com/15164633/43784511-4d940da0-9a32-11e8-8a54-4de13db8894d.png)

**Comment by kylebarron** [comment]
https://gist.github.com/kylebarron/e46ce79911976c3aae9d7e98309b9222

**Comment by kylebarron** [comment]
@mcaceresb Check out https://github.com/kylebarron/stata_kernel/blob/dev-stata-lexer/stata_kernel/stata_lexer.py

**Comment by kylebarron** [comment]
I believe I've implemented correct comments. Working on strings then writing some tests.

**Comment by kylebarron** [comment]
Yes that should be possible. Since Mata is only started with `mata` and ended with `end` (is this true?), I can easily find when Mata starts and ends and then just write a different lexer for Mata and use the Mata tokenizer on the Mata code.

**Comment by mcaceresb** [comment]
You need to be careful in that

1. `mata` can be preceded by any number of `CAPture`, `QUIetly`, or `Noisily`
2. `mata` can be followed by any number of spaces, `:`, and any number of spaces thereafter.
3. If there is anything else following mata, it is evaluated inline, and does not enter the mata environment
4. `end` can be preceded by any number of spaces and followed by __anything__
5. It doesn't matter where `end` appears. In a loop, a function, etc. The mata environment will end at that point.
6. `mata` is not nested, as `mata` itself is a valid `mata` command.

**Comment by kylebarron** [comment]
Thanks. I'll have to look at the mata syntax more closely.

**Comment by mcaceresb** [comment]
Comments are just C-style comments, except they can be nested. Rules for locals, etc. are the same. I don't think there is much to look out for within a mata block per se, other than the prompts are different.

**Comment by kylebarron** [comment]
I'll come back to Mata once I progress on some other stuff. You're welcome to submit a PR with a Mata lexer if you'd like. All it needs to support is comments and strings.
