### ISSUE TITLE
Crash from pygments when typing `%td`

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#295]
@mcaceresb 	
Just open up qtconsole and type `%td`. Does it crash for you too? This appears to be a pygments error.

It might be that `Token.Name.Format` is an unacceptable token name?

```
> jupyter qtconsole --kernel stata
Traceback (most recent call last):
  File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/qtconsole/frontend_widget.py", line 82, in highlightBlock
    super(FrontendHighlighter, self).highlightBlock(without_prompt)
  File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/qtconsole/pygments_highlighter.py", line 132, in highlightBlock
    self.setFormat(index, length, self._get_format(token))
  File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/qtconsole/pygments_highlighter.py", line 186, in _get_format
    result = self._get_format_from_style(token, self._style)
  File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/qtconsole/pygments_highlighter.py", line 202, in _get_format_from_style
    for key, value in style.style_for_token(token).items():
  File "/home/kyle/local/anaconda3/lib/python3.6/site-packages/pygments/style.py", line 106, in style_for_token
    t = cls._styles[token]
KeyError: Token.Name.Format
[1]    20061 abort (core dumped)  jupyter qtconsole --kernel stata
```

**Comment by kylebarron** [comment]
This only happens inside qtconsole, not the plain console

**Comment by mcaceresb** [comment]
Not really, but I take it I need to update pygments, right?

**Comment by kylebarron** [comment]
Well you'd notice if it crashed for you, because qtconsole quits. It's using the pygments that stata_kernel installs

**Comment by kylebarron** [comment]
It might be the style I'm using actually

**Comment by mcaceresb** [comment]
Just merged master and re-installed. I don't get a crash. What style do you use?

**Comment by kylebarron** [comment]
https://bitbucket.org/joon/color-schemes-for-jupyter-qt-console/src/cb27cfd7a713bb358be0b0c966bd11525842aa28/jupyter_qtconsole_colorschemes/material_light.py?at=master&fileviewer=file-view-default

It doesn't define a color for `Name.Format`, but I'm surprised jupyter crashes with it...

**Comment by mcaceresb** [comment]
I mean, I get that _every_ scheme crashes...

I don't know what the fix is. I think I should just change `Name.Format` to `Name.Other` or to `String.Other` (I think the latter might be better since it's highlighted more often in various styles) and then call it a day; the crash is worse than not always having highlighted formats.

**Comment by kylebarron** [comment]
So it does indeed crash for you?

**Comment by mcaceresb** [comment]
Yes. Just tried it.

**Comment by mcaceresb** [comment]
I mean, there's a bug in the regex for the `%td` format anyway, so I ought to update it. I thought the way pygments worked was that new tokens were defined on the fly, but I'd rather switch it to a built in token than try to figure out why that is not the case here. Let me know if you have a better idea, tho.

**Comment by kylebarron** [comment]
Ok, it's good you're able to reproduce it. I think you know Pygments better than I do. I've never looked at the styling side, only the lexer side. Take whatever action you think is best.

**Comment by mcaceresb** [comment]
`Name.Other` it is, then. It's not really a string, and it's typically between other stuff that _is_ highlighted so it's probably fine.

**Comment by mcaceresb** [comment]
This should now be updated in the pull request and in the `highlight-sas-stata` repo.

**Comment by kylebarron** [comment]
Great. I'll update it in this repo as well. Eventually when your pygments PR is merged and pygments is next released, the pygments files in this repo should be removed.
