### ISSUE TITLE
Hi I use StataIC and Jupyter cannot load the Kernel; I suspect there is a path problem

### ISSUE THREAD

**Issue by mkashiouris** [kylebarron/stata_kernel#296]
#### Problem description

- This should explain **why** the current behavior is a problem and why the expected output is a better solution.
- **Note**: Many problems can be resolved by simply upgrading `stata_kernel` to the latest version. Before submitting, please try:

    ```
    pip install stata_kernel --upgrade
    ```
    and check if your issue is fixed.

#### Debugging log

If possible, attach the text file located at

```
$HOME/.stata_kernel_cache/console_debug.log
```
where `$HOME` is your home directory. This will help us debug your problem quicker.

**NOTE: This file includes a history of your session. If you work with restricted data, do not include this file.**

#### Code Sample

Especially if you cannot attach the debugging log, please include a [minimal, complete, and verifiable example.](https://stackoverflow.com/help/mcve)

```stata
// Your code here

```

#### Other information

If you didn't attach the debugging log, please provide:

- Operating System
- Stata version
- Package version (You can find this by running `pip show stata_kernel` in your terminal.)

**Comment by kylebarron** [comment]
Are you using Mac?

**Comment by mkashiouris** [comment]
Hi thank you, i am using Mac and the Anaconda with Python 3.7 ... seems like the kernel cannot find the path, the instructions for previous versions were to include the pathname into the config file... but the config file now seems to be trying to find the stata path automatically...


On: 27 February 2019 09:51, "Kyle Barron" <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you using Mac?

**Comment by kylebarron** [comment]
I'll make an update soon to do this automatically, but for now you have to manually edit the configuration file (`~/.stata_kernel.conf`) and change `execution_mode=console` to `execution_mode=automation`.

This is Stata's fault because it doesn't ship with a console version for Stata IC for Mac. Your experience may be slower but there's nothing I can do about that.

See also: https://github.com/kylebarron/stata_kernel/issues/282

From Stata support:

> Unix operating systems often have an optional graphical user interface so we
> need to include console versions of Stata for all flavors of Stata on those
> systems. 
> 
> The Mac operating system always has a graphical user interface so the console
> version of Stata on the Mac is a special tool that is included for power users.
> The Stata/IC for Mac is designed for regular Stata users and does not include a
> console version.
> 
> Originally the Mac versions of Stata were just like the Windows versions and
> did not have any console support.

**Comment by kylebarron** [comment]
Let me know if that works for you.
Feel free to contact StataCorp as well and ask that they distribute the console with StataIC.

**Comment by mkashiouris** [comment]
i will try, thank you, i am waiting the STATA 16 to come out so i can buy the more expensive version that supports your awesome kernel


On: 27 February 2019 11:26, "Kyle Barron" <notifications@github.com<mailto:notifications@github.com>> wrote:

Let me know if that works for you.
Feel free to contact StataCorp as well and ask that they distribute the console with StataIC.

**Comment by kylebarron** [comment]
Sounds good. Hope Stata 16 doesn't have any new feature that breaks compatibility!
