### ISSUE TITLE
Cannot find confit file in system

### ISSUE THREAD

**Issue by nilshaakonlehr** [kylebarron/stata_kernel#297]
#### Problem description

Hi, I tried to install the kernel but I am running into the problem that the system cannot find Stata automatically. Your guidelines state that I should adjust the config file then, but I cannot find it. I tried searching for it (in the home directory and the stata_kernel folder), but I cannot locate it.

#### Code Sample

```

#### Expected Output

Can you deliver a config file that I could copy and paste to my system?

#### Other information

I am operating on the latest Mac OS with the lastest StataIC and just downloaded the kernel today.

**Comment by kylebarron** [comment]
There's no `stata_kernel` folder. The file is at `$HOME/.stata_kernel.conf` the `.conf` is just an extension. 

Also see #296 	and #282

**Comment by JDHernandez1** [comment]
If you type in the finder  `Shift+Cmd+.`   you might be able to see the **.stata_kernel.conf** file, and to modify it.
