### ISSUE TITLE
stata highlight labextension installation hangs

### ISSUE THREAD

**Issue by andwax** [kylebarron/stata_kernel#298]
#### Problem description

- installation of jupyterlab-stata-highlight hangs when Resolving Packages
-Specifically, it hangs at ``jupyterlab-stata-highlight@file:../extensions/jupyterlab-stata-highlight-0.1.1.tgz''
- **Note**: I have installed everything through conda with administrator priveledges, including Node.js and updating stata_kernel to 1.10.5. 

#### Debugging log

[stata-highlight-error.txt](https://github.com/kylebarron/stata_kernel/files/2942523/stata-highlight-error.txt)

#### Code Sample

jupyter labextension install jupyterlab-stata-highlight

#### Other information

- Windows 10 x64
- Stata 15 SE
- Package version: 1.10.5

**Comment by kylebarron** [comment]
Are you behind a firewall? I've seen that before, and it seems like `npm` just is unable to download the file.

**Comment by kylebarron** [comment]
I think you should be able to also separately download
```
https://github.com/kylebarron/jupyterlab-stata-highlight/archive/v0.1.1.zip
```
and then extract it, `cd` into `jupyterlab-stata-highlight-0.1.1` and run `jupyter labextension install .`

That worked for me

**Comment by andwax** [comment]
Yes, that makes sense, thanks for your feedback. unfortunately when I try
to install it locally along the lines of what you suggest it still goes to
npm to resolve packages and hangs on

`jupyterlab-stata-highlight@file
:../extensions/jupyterlab-stata-highlight-0.1.1-bca7db93805dde79fafacb2ea61d144e90915dae.tgz'

Do you know if this is a dependency?

**Comment by kylebarron** [comment]
Weird. Yes, running `jupyter labextension install .` still requires downloading dependencies from NPM. Not really sure if there's a good way around that.

**Comment by andwax** [comment]
OK, that's still helpful to know, thanks! I'm going to play with ways to see if I can get npm to work around my firewall then.
