### ISSUE TITLE
Fail to display simple graphs

### ISSUE THREAD

**Issue by JDHernandez1** [kylebarron/stata_kernel#299]
#### Problem description

Hello,

I have not been able to reproduce graphs using the stata_kernel on a jupyter notebook. 

I am loading a simple data set and using one variable to make a histogram. 

#### Code Sample

hist month

(bin=51, start=0, width=3.372549)

noi gr export ~/.stata_kernel_cache/graph$stata_kernel_graph_counter.png, width(600) replace

translator Graph2png not found
r(111);
.     global stata_kernel_graph_counter = $stata_kernel_graph_counter + 1
. }            
r(111);

###Note

It is recurrent to see this error after running any type of graph:

translator Graph2png not found
r(111);
r(111);
r(111);

#### Other information
- Operating System: macOS Mojave
- Stata version: 14.0/MP
- Package version: 1.10.5

Thanks in advance for the help

**Comment by kylebarron** [comment]
This means you can't export png graphs. Run 
```
%set graph_format svg --permanently
```
More info here: https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/#graph_format

**Comment by JDHernandez1** [comment]
The following error shows up: 

output-file suffix "svg" not recognized
    specify correct suffix or specify as() option
r(198);
r(198);
r(198);

Regards,

**Comment by kylebarron** [comment]
Do neither of the following code segments work for you?

```stata
sysuse auto
scatter price mpg
graph export test.png
```

```stata
sysuse auto
scatter price mpg
graph export test.svg
```

**Comment by JDHernandez1** [comment]
When execution_mode = console,  I always get the following: 

**translator Graph2png not found
r(111);
r(111);
r(111);**


However, when I change the execution_mode = automation before opening the jupyter notebook, the graphs will display on the notebook. Although, it is a little bit annoying because Stata needs to be opened. 

Regards,

**Comment by kylebarron** [comment]
Sorry, I meant not using Stata Kernel. Just in a regular Stata window.

**Comment by JDHernandez1** [comment]
The command works when exporting the png graph: **graph export test.png**. 

But if I run this **graph export test.svg** I get an error:  

**output-file suffix "svg" not recognized
    specify correct suffix or specify as() option**
