### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by TiesdeKok** [kylebarron/stata_kernel#3]
First of all, awesome work! I will try this kernel out on my Linux workstation soon and let you know if I run into any issues. 

I have been doing a little bit of research into Windows support but it seems that the Windows version does not have an interactive console mode (only the full GUI version or the console batch mode). It does appear that it is possible to install Stata without GUI, but I have not been able to get this to work yet (e.g. https://www.stata.com/support/faqs/windows/install-from-command-line/). 

Another option would be to include Stata Automation integration for Windows users (like I did with ipystata). I can probably add this for you once I get back from holiday in a couple of weeks. 

I will also definitely consider adding similar Linux (and MacOS) functionality into ipystata, by the looks of it this approach using `pexpect` seems to work nicely.

**Comment by kylebarron** [comment]
Yeah I'll definitely add Stata Automation for Windows and probably also Mac. It seems to work well generally with text and images so far. Though `more` can snag it.

**Comment by kylebarron** [comment]
I use Linux 95% of the time and Mac 5% so I was happy to find a solution that would work on Linux.

**Comment by TiesdeKok** [comment]
For sure, the batch mode on Linux has been bothering me for a long time as well. I tend to do most of my Stata prototyping on Windows and only execute polished code remotely on Linux servers so it was never too big of an issue for me. But I am glad you are working on this, it was certainly long over due!

**Comment by kylebarron** [comment]
I never use the terminal even on Linux. For the last year I've used my [Atom package](https://github.com/kylebarron/stata-exec/), which used `autokey` and now `xdotool` to copy and paste Stata code into the Stata GUI window. 

Making a true Stata kernel was something that I'd wanted to do for a while but just didn't think it was possible on Linux. But [Hydrogen](atom.io/packages/hydrogen) especially is amazing for an interactive development workflow, so it'll be great to use that with Stata. It lets me hit <kbd>ctrl</kbd>-<kbd>enter</kbd> locally, and the code is sent to Stata on the remote server, and the results come back inline next to the code. It's great! Though currently I have an issue with the kernel, just on Hydrogen. https://github.com/nteract/hydrogen/issues/1371

**Comment by kylebarron** [comment]
Preliminary Windows support now exists. As long as the code doesn't include `program`, `while`, `forvalues`, `foreach`, `input`, and `exit`. Also images support is still forthcoming.

**Comment by kylebarron** [comment]
@TiesdeKok There's still a long way to go actually. There are a lot of edge cases. But I think I'm well on my way to having a stable kernel. Maybe after this weekend I'll have a good, working example with few bugs.

**Comment by kylebarron** [comment]
Once I figure out a few more issues, I can go into detail about my methods in case you're interested.
