### ISSUE TITLE
Getting Started doc note on StataIC

### ISSUE THREAD

**Issue by nickeubank** [kylebarron/stata_kernel#301]
Seems like the docs on how to work with StataIC are broken?

![Screen Shot 2019-03-27 at 2 51 16 PM](https://user-images.githubusercontent.com/9683693/55107673-e3992f00-509f-11e9-9596-53152a9a7845.png)

**Comment by kylebarron** [comment]
Yeah... that was unintentionally pushed and then I've been too lazy/busy to actually fix it.

**Comment by kylebarron** [comment]
tl;dr change console to automation in the configuration file

**Comment by kylebarron** [comment]
Fixed with https://github.com/kylebarron/stata_kernel/commit/e646e32b52fa2076e506215e7b713ad72b3bc908
