### ISSUE TITLE
does not work with sysprofile

### ISSUE THREAD

**Issue by econwang** [kylebarron/stata_kernel#302]
At least on Linux, if I use `sysprofile.do` to change the ado path, stata kernel tends to die.

**Comment by mcaceresb** [comment]
How are you changing the ado path?

**Comment by econwang** [comment]
the content of my sysprofile.ado is:
```
sysdir set PERSONAL "/usr/local/ado/personal/"
sysdir set PLUS "/usr/local/ado/plus/"
```
which use system wide ado path for user-written ado, without loading this, stata kernel works fine.

**Comment by mcaceresb** [comment]
Can't reproduce on my Linux machine. Could you provide

- Stata kernel version
- Stata version
- Error message or behavior (it is not clear to me what "tends to die" means)
- Linux version (distro, kernel)

If you are able to run `adopath` after the kernel starts, please provide that output as well.

**Comment by econwang** [comment]
Stata kernel version: 1.10.5
Stata version: 14.2 MP
Error behavior: the kernel starts well, but with any command typed, shift + enter, then after about 10s, it shows `dead kernel`.
Linux version: Clear Linux

I can only run `adopath` in console, the output is:
```
. adopath
  [1]  (BASE)      "/usr/local/stata14/ado/base/"
  [2]  (SITE)      "/usr/local/ado/"
  [3]              "."
  [4]  (PERSONAL)  "/usr/local/ado/personal/"
  [5]  (PLUS)      "/usr/local/ado/plus/"
  [6]  (OLDPLACE)  "~/ado/"
```

**Comment by econwang** [comment]
the output of `console_debug.log:
```
Notes:
      1.  Unicode is supported; see help unicode_advice.
      2.  More than 2 billion observations are allowed; see help obs_advice.
      3.  Maximum number of variables is set to 5000; see help set_maxvar.

running /usr/local/stata14/sysprofile.do ...

--more--q^H^H^H^H^H^H^H^H        ^H^H^H^H^H^H^H^H.
```

**Comment by mcaceresb** [comment]
Try adding `set more off` to `sysprofile.do` and run `adopath` again?

**Comment by econwang** [comment]
does not help, don't know which induces the last line, now I find that no matter what I put in the sysprofile.do, the kernel will die, but without load it, stata kernel works well.

**Comment by econwang** [comment]
fixed by change the owner of `sysprofile.do` to root, thanks.

**Comment by kylebarron** [comment]
I remember having difficulty always getting past that initial `--more--` on different machines and user profiles. If you run `set more off, permanently`, you should at least be able to get to the initial prompt I think?

**Comment by econwang** [comment]
> I remember having difficulty always getting past that initial `--more--` on different machines and user profiles. If you run `set more off, permanently`, you should at least be able to get to the initial prompt I think?

Many thanks, `set more off, permanently` fix it
