### ISSUE TITLE
Fix broken link in Config.raise_config_error() method

### ISSUE THREAD

**Issue by afuetterer** [kylebarron/stata_kernel#303]
#### Problem description

The link in the raise_config_error() method in the Config class is broken.
see: <https://github.com/kylebarron/stata_kernel/blob/master/stata_kernel/config.py#L115>

I get 404 when accessing <https://kylebarron.dev/stata_kernel/user_guide/configuration/>. I think it should be <https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/> now. Do you want me to do a PR?

**Comment by mcaceresb** [comment]
Thanks for pointing it out. I fixed the link.

**Comment by afuetterer** [comment]
Great.
