### ISSUE TITLE
Stata 16 Support

### ISSUE THREAD

**Issue by StevenLi-DS** [kylebarron/stata_kernel#309]
Just saw this new update in Stata. Is there any plan to support Stata 16 buddy?

https://www.stata.com/new-in-stata/#

**Update:**

```
Versions:
stata-kernel: 1.10.5
jupyterlab: 1.1.4
notebook: 5.7.8
Stata: Stata IC 16
OS: Windows 10

Paths:
Stata: C:\Program Files\Stata16
.stata_kernel.conf: C:\Users\your_user_name
```
I was using Stata 15 and installed new Stata 16 after uninstalling version 15 and did the following:

1. register Stata 16 (i.e., link the Stata Automation library) via the step in the [doc](https://kylebarron.dev/stata_kernel/getting_started/#prerequisites):

2. change the Stata path in `.stata_kernel.conf`:
`stata_path = C:\Program Files\Stata16\StataIC-64.exe`

I tested with the [example notebook](https://nbviewer.jupyter.org/github/kylebarron/stata_kernel/blob/master/examples/Example.ipynb) and everything works fine with Stata 16

**Comment by lordflaron** [comment]
Not a developer, but I've used the kernel quite a bit. Have you tried just changing the executable in the config to point to Stata16? 

I wouldn't think that the versions would differ so much that Stata 16 wouldn't work.

**Comment by mcaceresb** [comment]
Well, as far as I cam tell the only issue would be python support, but I don't see that anything else in Stata 16 would be a problem for the kernel.

**Comment by StevenLi-DS** [comment]
@lordflaron haven't got my copy of it and will give it a shot once I get it.\

@mcaceresb Have you tried with 16? Is there anything I should be aware of?

**Comment by mcaceresb** [comment]
@StevenLi-DS I don't have Stata 16. I just meant that going through their "new in stata" page the only thing that would trip up the kernel is python support. (Maybe some new keywords won't be highlighted, but that's second order.) I do want to add python support to the kernel, in the style of mata support, but since I don't have access to Stata 16 that will have to wait for now.

**Comment by SiSeUniBE** [comment]
I'm using Stata 16 from within Atom via the stata_kernel already for some days now, and it works fine. As @mcaceresb already said, the execption is the integration of python into stata, which is not supported by the stata_kernel (it get stuck, if you try to use it). Great to hear that @mcaceresb plans to add python support to the kernel!
Unfortunetly, my python skills are too limited to contribute to that. However, I can confirm that it should be relatively straightforward to build the python support in the style of mata support, as python is integrated into stata very much the same way as mata is integrated into stata, which can be seen from the following examples, showing the three ways to call python interactively from within stata:
```
. // Enter Python interactive environment (with colon: exit python in case of error)
. python:
----------------------------------------------- python (type end to exit) ---------------------
>>> for x in range(3):
...         print(x)
0
1
2
>>> end
-----------------------------------------------------------------------------------------------

. 
. // Enter Python interactive environment (without colon: do not exit python in case of error)
. python
----------------------------------------------- python (type end to exit) ---------------------
>>> for x in range(3):
...         print(x)
0
1
2
>>> end
-----------------------------------------------------------------------------------------------

. 
. // Execute Python simple statement:
. python: print("hello world!")
hello world!
```

**Comment by StevenLi-DS** [comment]
@SiSeUniBE Hey buddy. I just got uninstalled my Stata 15 and installed Stata 16. I tried to run a command in my jupyter but it said "No Kernel". Would you mind if I ask what steps you went through to make Stata 16 works in jupyter?

**Comment by kylebarron** [comment]
I don't have access to Stata 16, and since it isn't free software, I have no free way to test this package on Stata.

**Comment by StevenLi-DS** [comment]
@kylebarron 
They have a short-term license though
https://www.stata.com/customer-service/short-term-license/

**Comment by kylebarron** [comment]
Well I'm not a student, and that license is valid for a week.

**Comment by mcaceresb** [comment]
@StevenLi-DS I wonder if it's simply the case that the path to your Stata program changed. In that case, you might want to try setting the new Stata path explicitly (see [here](https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/) for details).

If you can't figure out your new Stata path, you might want to try re-installing and see if that works.

**Comment by noahatchison** [comment]
I was able to successfully run the kernel with Stata16 by adding it to the subkeys in the the win_find_path function in utils.py and then rerunning  `python -m stata_kernel.install`. The function now reads:
`def win_find_path():
    import winreg
    reg = winreg.ConnectRegistry(None, winreg.HKEY_CLASSES_ROOT)
    subkeys = [
        r'Stata16Do\shell\do\command', r'Stata15Do\shell\do\command', 
        r'Stata14Do\shell\do\command', r'Stata13Do\shell\do\command', 
        r'Stata12Do\shell\do\command']

    fpath = ''
    for subkey in subkeys:
        try:
            key = winreg.OpenKey(reg, subkey)
            fpath = winreg.QueryValue(key, None).split('"')[1]
        except FileNotFoundError:
            pass
        if fpath:
            break

    return fpath`

**Comment by kylebarron** [comment]
@noahatchison good find. To be clear, that code is only run as a convenience to try to find Stata's path most of the time, but you can set the path manually by setting the `stata_path` configuration setting:
https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/#stata_path

I opened a PR to add that Stata 16 search string to the defaults:
https://github.com/kylebarron/stata_kernel/pull/330

**Comment by kylebarron** [comment]
@noahatchison a new release that includes that is on PyPI now: https://pypi.org/project/stata-kernel/1.11.1/
