### ISSUE TITLE
"Already preserved

### ISSUE THREAD

**Issue by akald** [kylebarron/stata_kernel#310]
Hi I keep getting an error saying the below. This seems to be for using preserve and restore function. When I copy and paste the code in Stata, it all works fine. It's just with Atom and the Stata kernel that the preserve and restore gives an error and breaks. Using the latest version of everything (atom, stata kernel etc): 

"
already preserved

r(621);
r(621);
"

- Operating System: Windows 10
- Stata version: 15
- Package version: Latest version

**Comment by mcaceresb** [comment]
I don't get this error running `preserve`. What is the code you are running, exactly? You just posted the error message.

**Comment by akald** [comment]
Please see attached for an example. Just running this code the second time generates this error. If I copy and paste the code in Stata, it runs just fine.

![Stata_Kernel Error](https://user-images.githubusercontent.com/54109434/63102421-08b90c00-bf73-11e9-82f9-7fb892df82fb.PNG)

**Comment by kylebarron** [comment]
This is because of your indentation. `restore` isn't being run, unless you highlight all five lines when you run it

**Comment by akald** [comment]
Thanks. I'm pressing Ctrl A and then run. Why would the indentation affect that? 

When I Ctrl A, copy, and paste the whole thing in Stata, it does work, though.
