### ISSUE TITLE
support start stata with enviroment variable

### ISSUE THREAD

**Issue by econwang** [kylebarron/stata_kernel#312]
Is there a way we can specify local enviroment varaible with the stata session on linux? usually we can use something like
```
env_xxx=xxx /path2stata/stata-mp
```
from console, or simplly use `alias`.

I have tried to change the `stata_path` in stata_kernel.conf, but then the kernel will not start

**Comment by mcaceresb** [comment]
That's not the way to start it. You need to start jupyter that way, and it will work:

```
$ env_xxx=xxx jupyter console --kernel stata

// startup messages

In [1]: disp `"`:env env_xxx'"'                                                                                                                              
xxx
```

**Comment by econwang** [comment]
Thanks, actually I use the jupyterlab and start several kernels, such as python, R and stata, if I start jupyterlab with `env_xxx=xxx`, then `env_xxx` will be inherited by all kernels, how to pass the `env_xxx` only to stata kernel?


> That's not the way to start it. You need to start jupyter that way, and it will work:
> 
> ```
> $ env_xxx=xxx jupyter console --kernel stata
> 
> // startup messages
> 
> In [1]: disp `"`:env env_xxx'"'                                                                                                                              
> xxx
> ```

**Comment by kylebarron** [comment]
I don't think it's possible to pass only to Stata kernel. Stata kernel inherits the environmental variables of whatever jupyter process starts it. So the only way to pass env vars to Stata is to start them with all of jupyter
