### ISSUE TITLE
Scatter plot creates r198  - Caused by space in username 

### ISSUE THREAD

**Issue by danfridman** [kylebarron/stata_kernel#314]
#### Problem description
Cannot create scatter plot. Give's error 
invalid 'Fridman'
r(198)
r(198)

#### Debugging log

[log2.log](https://github.com/kylebarron/stata_kernel/files/3772761/log2.log)

#### Code Sample

```stata
sysuse auto
scatter price mpg
```

![image](https://user-images.githubusercontent.com/45105185/67583927-9145ec80-f71a-11e9-8d4e-e2d20c00a196.png)

#### Expected Output
A scatter plot

#### Other information
It probably has to do with the space in my username. I've used a symlink (directory junction, C:\Dan points to C:\Users\Dan Fridman) to get around this in other cases, but couldn't figure out how to point stata_kernel to it.  

Installed: 
Windows 10 Enterprise 1803 17134.1069
Anaconda3 2019.10
Atom 1.41.0
Hydrogen 2.13.0
stata_kernel 1.10.5
Stata/SE 15.1 for Windows (64 bit x86-64)

**Comment by kylebarron** [comment]
Hmm, ideally it should work with a space, but I don't really have time to debug it. You could try changing your [`cache_directory`](https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/#cache_directory) using the [`%set` magic](https://kylebarron.dev/stata_kernel/using_stata_kernel/magics/#set)

**Comment by danfridman** [comment]
Awesome. 

I set it to C:\Dan\.stata_kernel_cache and it worked! 

Thanks!
