### ISSUE TITLE
output of any command is appended and prepended by a timestamp in jupyter or atom

### ISSUE THREAD

**Issue by mr-avila** [kylebarron/stata_kernel#315]
#### Problem description

The output of any command is appended and __prepended__ by something like a timestamp, as following 
```
di "hello"
r; t=0.00 18:44:44
hello
r; t=0.00 18:44:46
```
the funny thing is that it does not take that long (2 seconds) to run the command... it runs rather instantly... This happens using Atom and Jupyter Notebook. 

It wouldn't bother me much, but the output is passed onto the final PDF

#### I am using:
- **stata-kernel**, Version: 1.10.5
- Python 3.7.1
- jupyter notebook:  5.7.4
- `linux 4.19.79-1-MANJARO  x86_64 GNU/Linux`

## console_debug log

[console_debug.log](https://github.com/kylebarron/stata_kernel/files/3795202/console_debug.log)

## example image
![image](https://user-images.githubusercontent.com/31955632/67973821-8951e500-fc11-11e9-830c-7b038ffd316b.png)

**Comment by kylebarron** [comment]
This is just because you have `rmsg` set to on. [`rmsg`](https://www.stata.com/help.cgi?rmsg) times your commands. So that's saying that printing the graph took 0.09 seconds and finished at 19:05:48. To turn this off, run `set rmsg off, permanently`

**Comment by mr-avila** [comment]
Oh great! Thanks for the very quick response... I could have figured it out myself with a little more thinking and researching 🤦🏼‍♂️🤦🏼‍♂️
I hope, however, this issue helps someone else in the future.
