### ISSUE TITLE
markdown headers are not converted to white in Jupyter lab dark theme

### ISSUE THREAD

**Issue by StevenLi-DS** [kylebarron/stata_kernel#316]
![image](https://user-images.githubusercontent.com/33796896/68065753-f6de3e00-fd03-11e9-9b7d-f11483042b22.png)

```
jupyterlab: 1.1.4
stata-kernel: 1.10.5
OS: Windows 10
```

**Comment by kylebarron** [comment]
This is not an issue with this package, it has to do with your styling connected to hydrogen

**Comment by kylebarron** [comment]
Oh I see this is jupyterlab, not hydrogen. You should save this document with the headers, then make an issue on jupyterlab including the example document
