### ISSUE TITLE
ssc install to add new STATA commands

### ISSUE THREAD

**Issue by mariannevb** [kylebarron/stata_kernel#320]
This is not a problem or a bug.

I would like to be able to add STATA commands via 

ssc install <commandname>

For example, the command 'mdesc' which "describes" missing data, e.g., listing the number of missing observations in a variable, is very useful but is available only through

ssc install mdesc

Alternatives: I use a lot of these nonstandard commands, some of them have basic-STATA workarounds, and some don't.

**Comment by kylebarron** [comment]
This is just an interface to Stata. Have you tried `ssc install mdesc`?

**Comment by mariannevb** [comment]
I am so sorry. I mistyped it.  I feel pretty foolish!

Thank you, BTW, for making the stata kernel. I plan to use it in teaching
so I can distribute 'what we did in class' in a lovely format.  It's
especially great for loops that graph all the variables (in a small
dataset) to visually check for breaks and outliers.  I'm teaching Economics
students who are new to data work.

Marianne
