### ISSUE TITLE
comment/un-comment current line using ctrl+/

### ISSUE THREAD

**Issue by shuai-zhou** [kylebarron/stata_kernel#326]
I am new to stata_kernel. Maybe this is already a feature built-in stata_kernel, and I just picked up the wrong shortcut, but when I was trying to comment on a line using ctrl+/, it does not work.

**Comment by kylebarron** [comment]
It's an atom feature, not a stata kernel feature, and you must have language-stata installed https://atom.io/packages/language-stata
