### ISSUE TITLE
Systemwide config file path?

### ISSUE THREAD

**Issue by Carreau** [kylebarron/stata_kernel#327]
**Is your feature request related to a problem? Please describe.**

Hi, I'm deploying the stata kernel  on a jupyterhub. Right now I need to create a ~/.stata_kernel.conf file for each user the wish to use it. 

**Describe the solution you'd like**
I'd like to have a system wide file to which to load default config values. Do you have any objections ? I can make a pull request. If so do you have any preference for the system-wide config path ? 

**Describe alternatives you've considered**
Have each user manually create default config.

**Comment by mcaceresb** [comment]
I don't think it should be required, but allowing for a system-wide config sounds like a good idea. You mean to look for a system-wide config first, load it, and then update with the local config?

Yes, pull request would be good.

On linux maybe `/etc/stata_kernel.conf` is a natural place for a system-wide config. Less sure about Windows/OSX.

**Comment by Carreau** [comment]
> You mean to look for a system-wide config first, load it, and then update with the local config?

Yes that's what I meant.

> Less sure about Windows/OSX.

I doubt people deploy hubs on those, so I don't think that would be necessary.

**Comment by kylebarron** [comment]
First, thanks for all your work on Jupyter @Carreau !

The issue of a systemwide config for use with JupyterHub was raised once before: https://github.com/kylebarron/stata_kernel/issues/222

I appear to have merged something that I thought allowed to kernel to run without a config file: https://github.com/kylebarron/stata_kernel/pull/226

I don't think I ever added functionality for a system-wide config though.

cc: @mcaceresb

**Comment by Carreau** [comment]
> I appear to have merged something that I thought allowed to kernel to run without a config file: #226

Hum, at least for the cluster I deployed that for it did not work, I may have to dive into that more, and find out why it did not worked. It may be a weird interaction between sudospawner and setting PATH.

**Comment by mcaceresb** [comment]
#328 is now in master. Cheers.

**Comment by kylebarron** [comment]
@mcaceresb unless you have anything else you want to add, I'd be happy to push another release to pypi. Thoughts?

**Comment by mcaceresb** [comment]
@kylebarron I'm looking through other issues to see if there is something else I can feasibly clean up atm. What commit was the last release btw?

**Comment by kylebarron** [comment]
I think https://github.com/kylebarron/stata_kernel/commit/55adab0ea22708288bee97ab6ea0f19d23cb0b3e. It looks like 1.10.5 is the last PyPI release, even though a 1.10.6 commit exists... https://pypi.org/project/stata-kernel/

**Comment by kylebarron** [comment]
Pushed 1.11.0 https://pypi.org/project/stata-kernel/1.11.0/
If you could test it with Stata, that would be great @mcaceresb

**Comment by Carreau** [comment]
Awesome; I just updated on our jupyterHub and as far as I can tell this works. I'll put that in  a few students hands to get more feedback.

**Comment by kylebarron** [comment]
I don't have access to Stata anymore, and I don't know of a good way to test the parts that interact with Stata on something like Travis CI that doesn't have Stata, so it's good to make sure that nothing big breaks.
