### ISSUE TITLE
UnboundLocalError: local variable 'pdf_dup' referenced before assignment

### ISSUE THREAD

**Issue by Carreau** [kylebarron/stata_kernel#332]
Sorry indirectly reported so vague:

After `%set graph_format pdf --permanent`, kernel can't start because of unbound:

```
# in codemanager.py
        cache_dir = config.get('cache_dir')
        if graph_fmt == 'svg':
            pdf_dup = config.get('graph_svg_redundancy', 'True')
        elif graph_fmt == 'png':
            pdf_dup = config.get('graph_png_redundancy', 'False')
        pdf_dup = pdf_dup.lower() == 'true'
```

We can see that if it's neither `svg` or `png`, `pdf_dup.lower()` is unbound.

Not sure the best way to fix it and which fallback you like.

**Comment by kylebarron** [comment]
I think I wasn't planning for setting the `graph_format` to pdf, since in my testing Jupyter Notebook wasn't great at displaying PDFs. Maybe support is better now in JupyterLab, but in any case I should prevent this from raising an error.

**Comment by kylebarron** [comment]
I pushed 1.11.2 to PyPI, which should fix this.
