### ISSUE TITLE
for help : how can I use it with jupyter in vscode

### ISSUE THREAD

**Issue by drrui** [kylebarron/stata_kernel#340]
- Hi, the stata_kernel works well with my jupyter in anaconda3.  And I want to use it in vscode. But when I choose the kernel in vscode jupyter, there is no this kernel. So, how to make it work with the vscode(python extension) ? Thx very much~

- Operating System: win10
- Stata version: stata16
- Package version (1.11.2)

**Comment by kylebarron** [comment]
I don't think it's possible to use non python kernels in vscode

**Comment by drrui** [comment]
@kylebarron 😭

**Comment by mcaceresb** [comment]
@drrui Also see: https://github.com/microsoft/vscode-python/issues/5078

**Comment by drrui** [comment]
@mcaceresb Thank you~

**Comment by kylebarron** [comment]
Closing this as this is outside the scope of the package.
