### ISSUE TITLE
Magics not working

### ISSUE THREAD

**Issue by po4dun** [kylebarron/stata_kernel#342]
Hi 
Whenever I try magics in Atom or Jupyter, I get an error message:

   ```
 %head 
   ```

```
error: export: unknown subcommand "delimited"

usage: %head [-h] [N] [varlist] [if]
```

Didn't anyone having this issue before me

- Win 10
- Stata version 12
- Package version 1.10.5

**Comment by kylebarron** [comment]
The kernel runs [`export delimited`](https://www.stata.com/help.cgi?export) internally, and that might not be supported on Stata 12.

**Comment by po4dun** [comment]
It worked with Stata15, thus must have been a Stata version issue. Thanks!
