### ISSUE TITLE
License not applicable to this Stata - Stata-se 

### ISSUE THREAD

**Issue by Quinten-gs** [kylebarron/stata_kernel#344]
Dear @kylebarron, 

Thank you for your stata_kernel repo. 

Whilst installing the stata_kernel I came across the issue that my kernel died upon starting. 

When looking in the console_debug.log it said; 

> License not applicable to this Stata

I have Stata/SE 14 installed and can run it in cli using stata-se. When attempting to run stata-mp I get the same error message. Could it be that stata_kernel is configured to run stata-mp? Can I change it to stata-se? 

Best regards,
Quinten

**Comment by kylebarron** [comment]
What operating system are you on and you should check that that path to Stata is correct. https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/
You probably installed a new Stata where the old license expired

**Comment by Quinten-gs** [comment]
Hi Kyle, thank you for your quick reply. 

My OS is Ubuntu 18.04.4 LTS (Bionic Beaver). 

How and where would I set the path exactly? I set stata_path to /usr/local/stata14/stata in my tljh config file as seemingly indicated in the documentation and reloaded this new configuration however I still get a dead kernel on jupyter. 

Cheers, 
Quinten

**Comment by mcaceresb** [comment]
@Quinten-gs The config file is in `~/.stata_kernel.conf`

You may need to set the `se` explicitly. Maybe

```
[stata_kernel]
stata_path = /usr/local/stata14/stata-se
execution_mode = console
```

?

**Comment by Quinten-gs** [comment]
This indeed solved the issue. Thank you very much @mcaceresb!
