### ISSUE TITLE
`c(os)' reports MacOSX from Stata, and Unix from stata_kernel

### ISSUE THREAD

**Issue by rhstanton** [kylebarron/stata_kernel#350]
#### Problem description

I often use the output of c(os) to determine how to set up various directories in my Stata code (which I run on various different machines).

When I run

```stata
display "`c(os)'"
```

directly in Stata on my Mac, it returns "MacOSX"

The same command in a Jupyter notebook instead returns "Unix"

#### Code Sample

See above.

- Operating System: OSX 10.15.5
- Stata version: 15.1
- Package version:  1.11.2

**Comment by kylebarron** [comment]
This is probably an issue with Stata. You should open up the command-line version of Stata for Mac, and test `display "`c(os)'"` there; I bet it will say `Unix`.

The path to the command-line version of Stata should be something like
```
/Applications/Stata/StataSE.app/Contents/MacOS/stata-se
```
or
```
/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp
```

If you paste that into the terminal, you should open a stata session in the terminal.

Guessing that I'm right you'd have to use `execution_mode=automation` for `c(os)` to be correct.

**Comment by rhstanton** [comment]
Thanks! That does seem to be the issue. It seems there are advantages to using the console version, so I’ll just find another way to tell what machine I’m running on.

**Comment by kylebarron** [comment]
The console version is generally faster I believe.

I don't think there's anything I can do. You could send a bug report to StataCorp, but they haven't been too welcoming of Mac console bug reports in the past.
