### ISSUE TITLE
kernel dead after pip install stata_kernel --upgrade

### ISSUE THREAD

**Issue by charlieeatonphd** [kylebarron/stata_kernel#359]
#### Problem description

- I ran "pip install stata_kernel --upgrade" on Mac OS Catalina as suggested because of some glitchy stuff with graphing with the kernel. But now the kernel is dead and cannot be restarted. I get this error message:

[E 15:20:00.857 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 46889434-e28e-4292-aeab-6b3980f30415

- Operating System: Mac OS catalina
- Stata version: 15.1
- Package version: 1.12.0

**Comment by kylebarron** [comment]
That sounds like an error from an existing Jupyter session; can you try starting a new session?

**Comment by charlieeatonphd** [comment]
I shutdown Jupyter and reopened it. None of my Jupyter kernels work now actually. Same error for Python and R kernels

**Comment by charlieeatonphd** [comment]
Based on this: https://github.com/jupyter/notebook/issues/4050

I ran the following which fixed the kernel problem:

pip install ipython==7 prompt-toolkit==2.0.10 jupyter-console==6.0.0

I'll open a separate issue for the graphing glitch which remains after the kernel update.

Thanks for all your great work on the kernel. It's such an amazing tool.

**Comment by Carreau** [comment]
hi @charlieeatonphd sorry I saw you mail only today. 
If it also affect Python kernel, you can try to run in a separate terminal 

`$ python -m ipykernel`, and see if there are error there. I'm not quite sure why the command above fixed it for you, it is strange.

**Comment by schadalapaka** [comment]
Hi @Carreau - hope you're well!!

One other researcher has a similar issue -and they have an Ubuntu OS on their machine. They installed Stata 16 before trying to set up Jupyter notebook and the stata kernel. 
Please let me know if you need any further information to help fix the issue.

Thanks
Sarvani
