### ISSUE TITLE
Could jupyter be removed from the dependencies?

### ISSUE THREAD

**Issue by stanmart** [kylebarron/stata_kernel#361]
When working with conda environments it is usual to have jupyter (and jupyter lab, notebook, etc.) installed in one environment only (e.g. base), and only install ipykernel into the other environments that are to be used in jupyter notebook or lab. However for stata_kernel jupyter is listed as a requirement, therefore all the jupyter machinery will be installed when installing it into an environment.

Is jupyter really necessary, or would ipykernel be enough as a requirement? Removing it would allow for more lightweight conda envs.

**Comment by kylebarron** [comment]
Is that usual? When I use conda environments I install all the dependencies I need in every environment. If you only install Jupyter in the base env, is it still accessible inside the other env? If so, this should be moot because pip will see that jupyter already exists and won't install another copy.

**Comment by stanmart** [comment]
If Jupyter is installed in the base env then you might have to start the notebook from there (I'm not sure on this one as the base environments' bin folder is visible for any environment, might or might not be the same for the scripts folder), but upon opening a notebook or console you can choose any of the environments that have ipykernel installed. Also, if the environment where jupyter is installed is added to the path in your shell then you can run its executables from any environment.

I thought I read somewhere that it is the preferred way of using notebooks with multiple environments but I cannot find the source so I might have been wrong :/ It's definitely one of the valid options, though: [SO question](https://stackoverflow.com/questions/58068818/how-to-use-jupyter-notebooks-in-a-conda-environment)

The issue is that pip will install another copy because it (correctly) sees that jupyter is not installed in that environment. The fact that jupyter executables are on the search path does not influence pip's behavior.
