### ISSUE TITLE
stata configuration file is missing

### ISSUE THREAD

**Issue by lgonzalez104** [kylebarron/stata_kernel#362]
I have an Ubuntu OS. When I install using python -m stata_kernel.install, the terminal presents this error: 

ValueError: stata_path option in configuration file is missing or invalid

The problem is that when I search for the hidden configuration file (.stata_kernel.conf) to adjust the string path to Stata, it is not anywhere (as the error says, the file might be "missing"). Do you know how can I solve this issue?

Thank you in advance

**Comment by kylebarron** [comment]
The path is in your home directory `~/.stata_kernel.conf`

**Comment by lgonzalez104** [comment]
Dear Kyle Barron. Thank for your quick answer. That is the issue, when exploring with 'ls -a' command, the file is not in my home directory (nor in the parent directories). The only one I have found is '.stata_kernel_cache'
Best,

**Comment by kylebarron** [comment]
Maybe there's an error in the install script. When you run `python -m stata_kernel.install`, do you see

> WARNING: Could not find Stata path. Refer to the documentation to see how to set it manually:

**Comment by lgonzalez104** [comment]
Yes. That is the error that appears. But then the documentation indicates me to modify '.stata_kernel.conf'. But I can't because the hidden file is not anywhere nor in my home directory or any parent directory

**Comment by kylebarron** [comment]
Can you provide the entire output? Do you get a traceback? Does the command execute fine?

**Comment by lgonzalez104** [comment]
Thank you for your response. Yes, this is the output: 

(base) rub@rub-ThinkPad-E570:~$ python -m stata_kernel.install
Traceback (most recent call last):
  File "/home/rub/anaconda3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/rub/anaconda3/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/rub/anaconda3/lib/python3.8/site-packages/stata_kernel/__init__.py", line 5, in <module>
    from .kernel import StataKernel
  File "/home/rub/anaconda3/lib/python3.8/site-packages/stata_kernel/kernel.py", line 16, in <module>
    from .config import config
  File "/home/rub/anaconda3/lib/python3.8/site-packages/stata_kernel/config.py", line 150, in <module>
    config = Config()
  File "/home/rub/anaconda3/lib/python3.8/site-packages/stata_kernel/config.py", line 65, in __init__
    self.raise_config_error('stata_path')
  File "/home/rub/anaconda3/lib/python3.8/site-packages/stata_kernel/config.py", line 140, in raise_config_error
    raise ValueError(dedent(msg))
ValueError: stata_path option in configuration file is missing or invalid
Refer to the documentation to see how to set it manually:

https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/

**Comment by kylebarron** [comment]
Thanks, I think #363 should fix it
