### ISSUE TITLE
Can't install on mac with StataIC

### ISSUE THREAD

**Issue by araujo1987** [kylebarron/stata_kernel#365]
I'm having trouble installing the kernel on my macbook pro (Catalina OS). I can run "pip install stata_kernel" successfully, though it does **not** generate a ".stata_kernel.conf" file. I created my own with the following content:

_[stata_kernel]
stata_path = /Applications/Stata/StataIC.app
execution_mode = automation_

Every time I run "python -m stata_kernel.install" I get the following message:

_Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/__init__.py", line 5, in <module>
    from .kernel import StataKernel
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/kernel.py", line 16, in <module>
    from .config import config
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/config.py", line 171, in <module>
    config = Config()
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/config.py", line 86, in __init__
    self.raise_config_error('stata_path')
  File "/opt/anaconda3/lib/python3.7/site-packages/stata_kernel/config.py", line 161, in raise_config_error
    raise ValueError(dedent(msg))
ValueError: stata_path option in configuration file is missing or invalid
Refer to the documentation to see how to set it manually:

https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/_

I'm obviously not good at this, so I'm maybe making a simple mistake?

**Comment by kylebarron** [comment]
> I can run "pip install stata_kernel" successfully, though it does **not** generate a ".stata_kernel.conf" file

Did you run both
```py
pip install stata_kernel
python -m stata_kernel.install
```
?

**Comment by araujo1987** [comment]
Yes, I did. Here were my steps:

1. Run both commands and got that error message. 
2. Went looking for the configuration file (to change the stata path), but couldn't find it 
3. Created a .stata_kernel.conf file as described, keep getting the exact same error message.

**Comment by kylebarron** [comment]
Oh it's because `/Applications/Stata/StataIC.app` isn't the right path... that's a folder not an executable. It should look something like
```
/Applications/Stata/StataIC.app/Contents/MacOS/StataIC
```

If you paste that into a terminal it should open up the Stata window

**Comment by araujo1987** [comment]
Just tried that, same error (though it does open Stata when I type it on terminal). 

This is the config file I created, which is in the Home (Users) directory:

![Screen Shot 2020-10-14 at 10 35 09 PM](https://user-images.githubusercontent.com/30048640/96070095-86292680-0e6d-11eb-867a-6bf2ed72a75d.png)

**Comment by kylebarron** [comment]
What's your error traceback? The kernel isn't finding the path to stata. The configuration should look something like
https://github.com/kylebarron/stata_kernel/blob/fcdf18645b957b2cc5832c71dee28da9ee20a4c2/stata_kernel/config.py#L53-L60

**Comment by araujo1987** [comment]
I don't know what "error traceback" means exactly, but here's a screenshot:

![Screen Shot 2020-10-14 at 10 47 02 PM](https://user-images.githubusercontent.com/30048640/96070950-30ee1480-0e6f-11eb-8297-67117ce7d8fe.png)

And here's the config file I'm using now:

[stata_kernel]
stata_path = /Applications/Stata/StataIC.app/Contents/MacOS/StataIC
execution_mode = automation
cache_directory = ~/.stata_kernel_cache 
autocomplete_closing_symbol = False 
graph_format = svg 
graph_scale = 1 
user_graph_keywords = coefplot,vioplot

**Comment by kylebarron** [comment]
I don't think there's an easy way for me to debug that further with you. Maybe @mcaceresb has some thoughts

**Comment by araujo1987** [comment]
Well, thanks for trying to help. As I said, this is not my natural habitat and I might have missed something basic.
