### ISSUE TITLE
problem with %head and graph generation

### ISSUE THREAD

**Issue by knhjc** [kylebarron/stata_kernel#368]
#### Problem description
When I use the jupyter lab with the stata_kernel and run the code %head and codes related to graph generation, I get error "error: invalid 'Huang' ",  and 
"invalid 'Huang' 
r(198);
r(198);
r(198);"

my guesses are that this problem has something to do with my user name "William Huang" (where there's a white space) and the .stata_kernel.conf file which is located at "C:\Users\William Huang". 

However, I don't know what is wrong and how to fix it, since I am just a beginner in using jupyter and stata.

btw, I wish to have the graph generation results appear directly on the web page, instead of a new-opened svg or png file popping out to me. What should I do?

#### Debugging log

[console_debug.log](https://github.com/kylebarron/stata_kernel/files/5602219/console_debug.log)

#### Code Sample

```stata
// Your code here
* Simple time-series plot for each of first 10 individuals
qui xtline lwage if id<=10, overlay legend(off) saving(lwage_ts, replace)
qui xtline wks if id<=10, overlay legend(off) saving(wks_ts, replace)
graph combine lwage_ts.gph wks_ts.gph, iscale(1)

%head
```

Thank you very much for your time! Your kind help is appreciated.

**Comment by mcaceresb** [comment]
@knhjc I submitted a PR to fix the issue. As a temporary fix, can you try setting

```
cache_dir = "~/.stata_kernel_cache"
```

In your config file and see if that does the trick?
