### ISSUE TITLE
Graphing Issue Stata 16 and Windows

### ISSUE THREAD

**Issue by adityanz** [kylebarron/stata_kernel#370]
#### Problem description

- I am unable to render any graphs with state 16 and the jupyter notebook. Am getting this output. Regression output works fine

#### Debugging log

[Log File Link
](https://www.dropbox.com/s/k7v26w3b9ff24c2/console_debug.log?dl=0)
**NOTE: This file includes a history of your session. If you work with restricted data, do not include this file.**

#### Code Sample
Especially if you cannot attach the debugging log, please include a [minimal, complete, and verifiable example.](https://stackoverflow.com/help/mcve)

```stata
// Your code here
scatter close_zm
```
####  Output
invalid 'Dixit' 
r(198);
r(198);
#### Other information

If you didn't attach the debugging log, please provide:

- Operating System: Windows 10.0.19041.572
- Stata version: StataIC 16 Nov 19 2020
- Package version (You can find this by running `pip show stata_kernel` in your terminal.)
1.12.1

**Comment by mcaceresb** [comment]
This seems to be a very similar issue as in #369. I just submitted a new PR to fix.
