### ISSUE TITLE
Trying to use a stata kernel with nbgrader

### ISSUE THREAD

**Issue by perllaghu** [kylebarron/stata_kernel#373]
## A bit of a long into to get to the problem, apologies

I'm trying to get nbgrader (https://github.com/jupyter/nbgrader) to work properly with a stata kernel.

I have everything working apart from the grading functionality.

When autograding, nbgrader basically runs the notebook, and uses the cell outputs to determine the points to award for each cell.

When awarding marks to a cell, nbgrader checks the output of the cell & makes some deductions (see https://github.com/jupyter/nbgrader/blob/master/nbgrader/utils.py#L97-L130 )

There are three states that are looked for:

1. `output.output_type == 'error' or output.output_type == "stream" and output.name == "stderr":` (errors / failures get 0 points)

This is best exemplified with the pythonic

    # YOUR CODE HERE
    raise NotImplementedError()

I thought was the right solution:

    * YOUR CODE HERE
    display as error "index variable not found"

.... but apparently not as it gives a cell output of
```
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "index variable not found\n"
     ]
    }
   ],
```
..... so obviously that's not actually raising an error.

2. `output.output_type == 'execute_result'` (calculate some partial credit value)

This is where you get the cell to output a numeric, and can therefore use that to determine a partial credit.

(I've not tried that one in python... but all the outputs I've seen for the stata kernel seem to be `streams` - so I don't hold much hope there)

3. _anything else_ gets full points.

### understandable behaviour

Source cell:
```
display $points
```

output of cell:
```
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n"
     ]
    }
   ],
```
### Wrong / misunderstood behaviour

Source cell (syntax error.... I'm getting desperate):
```
gen foo = "foo"
if "$foo" != "bar" {
  display error
}
```

output of cell:

```
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "error not found\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "r(111);\n",
      "r(111);\n",
      "r(111);\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\n"
     ]
    }
   ],
```
So nearly...... but where do those last 3 blank lines come from? They trump the error before it - which means the cell _passes_, and gets full points.

### Questions

* Is there a way in stata to actually emit a "Raised Error" thing in Stata?

Pythonic errors output:
```
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'matplotlib'",
     "output_type": "error",
     "traceback": [
          ..... <snip>
     ]
    }
```
* Can I do something to stop these extra sections of outputs appearing?

#### Other information

If you didn't attach the debugging log, please provide:

- Ubuntu 18:04 in a Docekr Notebook ( jupyter/minimal-notebook:dc9744740e12 )
- Stata version - installed from Stata16Linux64.tar.gz
- Package version 1.12.2

**Comment by mcaceresb** [comment]
While Stata doesn't have a notion of an error in the same way other languages do, there is a way to raise errors in Stata. `error #` will return an error with code `#` and display the error message. `display as error` simply displays the text as if it was error text, but does not actually raise an error.

```
error 198
```

will print

```
invalid syntax
r(198);
```

Stata here raises error code 198; however, this does not get passed up to wherever you are calling Stata from. I do believe @kylebarron does some parsing of the error code, but  I don't know if this gets set in a way that can be used by `nbgrader`

**Comment by perllaghu** [comment]
@mcaceresb - thanks for this.... 

Yep, you're right: an error is not filtered up:

```
    "* YOUR CODE HERE\n",
    "error 198"
```
 has an output of
```
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "invalid syntax\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "r(198);\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
```
.... again, the trailing `newline` output set trumps the actual error, and the cell is seen as a _not fail_

## However!

a straight `exit` is:

```
* YOUR CODE HERE
exit 198
```
has an output of
```
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "r(198);\n"
     ]
    }
   ],
```

I'll now see if I can figure out some `if` test that will allow me to do something with this.

looking good

**Comment by perllaghu** [comment]
so close..... I thought I had it.... but no...

```
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "deletable": false,
    "nbgrader": {
     "cell_type": "code",
     "checksum": "264c3b0f483c6f29f612ff3ebd583ab7",
     "grade": false,
     "grade_id": "cell-8c0f9b95aba1e28a",
     "locked": false,
     "schema_version": 3,
     "solution": true,
     "task": false
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--Break--\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "r(1);\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "* Now import your fund data. If you are using default data use the file my_fundsX.csv, where X is the last digit of your B-number.\n",
    "\n",
    "* YOUR CODE HERE\n",
    "error 1"
   ]
  },
```

More trying things..

**Comment by mcaceresb** [comment]
@perllaghu Is the issue that there is stdout in addition to stderr? If yo sou would need to call `exit 1` instead of `error 1` since  the latter prints the error message associated with the error code.

**Comment by perllaghu** [comment]
Oh, I'll be so p*$$'d off if it was that simple!

Back to the hackery!

:smile:

**Comment by perllaghu** [comment]
I think I'm last my comprehension of Stata now... my `exit`'s are failing with things like
```
no; dataset in memory has changed since last saved
    Save the data or specify option clear to exit anyway.
r(4);
```

I think I need to throw this particular problem back to the academic who's teaching Stata

**Comment by mcaceresb** [comment]
@perllaghu Try an error code that has no message. For instance, throw `error 999`

**Comment by perllaghu** [comment]
I took some time away for coding work, and holidays - back to this.

The code in nbgrader that does the points allocation is here (as of 5/Jan, 2021): https://github.com/jupyter/nbgrader/blob/master/nbgrader/utils.py#L97-L130 

.... and I'm looking at lines 118/119 specifically

`error 192` is also a non-message error - so here's the json fragment for a cell with just an error in it:

```
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "cell_type": "code",
     "checksum": "92bf06c42cdfcd097cc2204c4f34084c",
     "grade": true,
     "grade_id": "cell-238f9e9df13c5ef0",
     "locked": true,
     "points": 1,
     "schema_version": 3,
     "solution": false,
     "task": false
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "r(192);\n"
     ]
    }
   ],
   "source": [
    "error 192"
   ]
  },
```

.... but it's still being seen as a non-failure, therefore awarded full marks

(this is what various Python errors output:
```
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "Missing parentheses in call to 'print'. Did you mean print(1)? (<ipython-input-1-c94594b6b28f>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-1-c94594b6b28f>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    print 1\u001b[0m\n\u001b[0m          ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m Missing parentheses in call to 'print'. Did you mean print(1)?\n"
     ]
    }
   ],
   "source": [
    "print 1"
   ]
  },
```
or
```
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "Exception",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mException\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-2aee0157c87b>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mraise\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mException\u001b[0m: "
     ]
    }
   ],
   "source": [
    "raise Exception"
   ]
  },
```
or
```
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "ename": "AssertionError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-7-a871fdc9ebee>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32massert\u001b[0m \u001b[0;32mFalse\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mAssertionError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "assert False"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
```

(all specifically `"output_type": "error"`)

**Comment by mcaceresb** [comment]
@perllaghu Are you using the latest version? The logic

`output.output_type == 'error' or output.output_type == "stream" and output.name == "stderr":`

means the Stata failure should register that as True, no? This is a relatively recent addition and the latest release is from well before it was made. It seems the solution might be to update nbgrader?

**Comment by perllaghu** [comment]
**arrggghhhh**

We're using commit point b5ae9f895c1774e61fecfab1d0106e537ce072da - which predates this

<censored> <censored> <censored> <censored> <censored>

Let me try that

**Comment by perllaghu** [comment]
Yep.....

Hand up..... Error was between seat & keyboard at this end!
