### ISSUE TITLE
Graph rendering in Github for Mac/Linux

### ISSUE THREAD

**Issue by charlieeatonphd** [kylebarron/stata_kernel#382]
Is there any way to produce graphs within a Stata kernel notebook on a Mac or Linux machine so that the graphs will render on github without having to use NBviewer?

**Comment by kylebarron** [comment]
You can check out the svg and png graph redundancy options and try it out on Github. I'd assume github would render a png.
https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/#graph_png_redundancy

**Comment by charlieeatonphd** [comment]
graph_svg_redundancy = True does lead the JupyterNotebook export pdf to
render the graph. But the kernel stalls if I specify graph_png_redundancy =
True.

I assume this is because I cannot %set graph_format png using console with
the Stata kernel. Is there another value for graph_svg_redundancy that
would create a redundant png? Am I missing something else?

**Comment by kylebarron** [comment]
I don't recall any fine details, but that summary sounds correct.

**Comment by charlieeatonphd** [comment]
Within the hidden .stata_kernel.conf file, I used a text editor to change the following configuration settings to the following values:
```
execution_mode = automation
graph_format = png
graph_png_redundancy = True
graph_svg_redundancy = False
```
This worked. After doing so, graphs from a Stata Kernel Jupyter Notebook on my Mac render in GitHub.

We'll see how well I tolerate working in automation instead of console execution mode.

**Comment by kylebarron** [comment]
Good to know. I think if you set `graph_format = png` you don't also need `graph_png_redundancy = True`; that's only important for when the main graph format isn't png.

**Comment by charlieeatonphd** [comment]
When I set the graph format to png, the graphs are rendered strangely small
within the Jupyter Notebook - much smaller than the GUI display that pops
up in the Stata graph viewer when running in automation mode. Any ideas for
how to increase the display size of the graph within the Notebook?
Best,
Charlie
[image: photo]
*Charlie Eaton (he/him)*
Assistant Professor of Sociology, UC Merced
Affiliated Faculty, UC Berkeley Center for Studies in Higher Education
web: faculty.ucmerced.edu/ceaton2/
<https://twitter.com/charlieeatonphd>
<https://www.facebook.com/eaton.charlie>

**Comment by charlieeatonphd** [comment]
Curiously, the small size problem is much worse with graphs where I have
used Stata's "graph combine" or "grc1leg"
Best,
Charlie
[image: photo]
*Charlie Eaton (he/him)*
Assistant Professor of Sociology, UC Merced
Affiliated Faculty, UC Berkeley Center for Studies in Higher Education
web: faculty.ucmerced.edu/ceaton2/
<https://twitter.com/charlieeatonphd>
<https://www.facebook.com/eaton.charlie>

**Comment by charlieeatonphd** [comment]
Apologies, Kyle of course already addressed the size issue. Simply use
magic "%set graph_width" I used "%set graph_width 1200" and that looks
pretty good. 1200 is number of pixels. But any number will work. See Kyle's
documentation here:
https://kylebarron.dev/stata_kernel/using_stata_kernel/configuration/#graph_width
Best,
Charlie
[image: photo]
*Charlie Eaton (he/him)*
Assistant Professor of Sociology, UC Merced
Affiliated Faculty, UC Berkeley Center for Studies in Higher Education
web: faculty.ucmerced.edu/ceaton2/
<https://twitter.com/charlieeatonphd>
<https://www.facebook.com/eaton.charlie>

**Comment by charlieeatonphd** [comment]
I'm finding it easier to fix the sizing issue with the graph_scale configuration. When producing Notebooks with png's in automation mode to render on Github, I change the scale from 1 to 2 ala

`graph_scale = 2`

when graphing in console with svg format, a scale of about 1 is better ala

`graph_scale = 1`
