### ISSUE TITLE
text/plain mime type unavailable for %help

### ISSUE THREAD

**Issue by roblem** [kylebarron/stata_kernel#384]
`text/plain` output available for `%browse` and `%head` but not `%help`

When I look at the code for magics, it appears that the intent was to include text/plain:
https://github.com/kylebarron/stata_kernel/blob/bb4e06fb4072d1ecb686898b4703a804cc6e4e47/stata_kernel/stata_magics.py#L569
but when I ask for that I get this warning/error (note this is an emacs src block, but the syntax is fine):
```
#+BEGIN_SRC jupyter-stata :session stata :exports both :display text/plain 
 %help regress
#+END_SRC

#+RESULTS:
: This front-end cannot display HTML help.
```
Note, for `%head` with `text/plain` we get the correct output:
```
#+BEGIN_SRC jupyter-stata :session stata :display text/plain
 %head 5 price mpg if mpg < 20 
#+END_SRC

#+RESULTS:
#+begin_example

     +--------------+
     |  price   mpg |
     |--------------|
  2. |  4,749    17 |
  5. |  7,827    15 |
  6. |  5,788    18 |
  9. | 10,372    16 |
 10. |  4,082    19 |
     +--------------+
#+end_example

```

**Comment by roblem** [comment]
Although realistically `help` works fine, provides the correct mime typle and is shorter to type, so maybe this isn't necessary.

**Comment by kylebarron** [comment]
> it appears that the intent was to include text/plain

https://github.com/kylebarron/stata_kernel/blob/30666154ba1eb45faa94003265b617f41ac21700/stata_kernel/stata_magics.py#L565-L570

If you look at the declaration of `_msg_plain`, that's just the plain-text error message to say help isn't supported for non-html viewers:

https://github.com/kylebarron/stata_kernel/blob/30666154ba1eb45faa94003265b617f41ac21700/stata_kernel/stata_magics.py#L111-L129

Currently the only way to fetch help is by fetching the `/help.cgi` URL, and we haven't implemented any way to do HTML to plain text translation

**Comment by mcaceresb** [comment]
> Although realistically `help` works fine, provides the correct mime typle and is shorter to type, so maybe this isn't necessary.

@roblem This is true. The point of %help is to provide  a formatted  version of the help page if HTML is supported. If you want the plain text equivalent then `help` will do so there is no reason for the  magic to support plain text. Perhaps the error message should say this?

**Comment by roblem** [comment]
Perhaps a clearer message would be nice.  In reality, I wasn't looking to use it in production- I was just trying to replicate the atom animated gif in emacs for a demo that I am adding to the docs.  Going to close.
