### ISSUE TITLE
Cannot send stata code through ATOM

### ISSUE THREAD

**Issue by nico-tse226** [kylebarron/stata_kernel#386]
Whenever I try to send stata code, (eg: display "Hello world") I get the following message

![Capture d’écran du 2021-04-21 15-01-44](https://user-images.githubusercontent.com/82656327/115557971-87bb2780-a2b2-11eb-9f6e-6c17a6777073.png)

Atom: 1.56.0
OS:Ubuntu 20.04 LTS

**Non-Core Packages**
Hydrogen: 2.15.3
language-stata 1.7.3

**Other**
Anaconda: 3-2020.11-Linux-x86_64
stata_kernel v3

**Comment by kylebarron** [comment]
> The command was not found or was not executable: None

Probably means the Stata executable wasn't found automatically on install. You should check your `~/.stata_kernel.conf` file to see if a Stata executable path is listed.

**Comment by nico-tse226** [comment]
Thank you so much, no It works perfectly !

I have modified the ~/.stata_kernel.conf file such as

stata_path = "/usr/local/bin/stata-mp"

Then, I have copied the file stata-mp from its inital folder to bin:

`sudo cp /usr/local/stata16/stata-mp /usr/bin`

Cheers !

Nicolas
