### ISSUE TITLE
can we use stata_excute and stata-kernel simulatenously with different short cut

### ISSUE THREAD

**Issue by fredericky123** [kylebarron/stata_kernel#388]
**Is your feature request related to a problem? Please describe.**
for mac os, can we use stata_excute and stata-kernel simulatenously with different short cut?
beacuse sometimes we need to manage data at the window of Stata
right now, the results pop up without openning window of Stata

**Describe the solution you'd like**
ctrl enter=using stata_excute; command enter= using stata_kernel

**Comment by kylebarron** [comment]
You don't say what execution environment you're using. If it's Atom you can easily override keybindings

**Comment by fredericky123** [comment]
> You don't say what execution environment you're using. If it's Atom you can easily override keybindings

Exactly, I am using Atom. I am a green hand of Atom, so I don't konow how to override keybindings, can you please show me a little more?
By the way, can the stata_kernal also be used at Sublime since you ask me about the environment?

**Comment by kylebarron** [comment]
https://stackoverflow.com/questions/43627165/how-to-change-atom-keybindings
https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/

This is unrelated to stata kernel itself. The keybindings are done through Hydrogen, the Atom package itself.

I don't think there's a way to use it within sublime, but I don't use sublime.
