### ISSUE TITLE
graph display bug

### ISSUE THREAD

**Issue by ZHULOO** [kylebarron/stata_kernel#391]
#### Problem description

- This should explain **why** the current behavior is a problem and why the expected output is a better solution.
- **Note**: Many problems can be resolved by simply upgrading `stata_kernel` to the latest version. Before submitting, please try:

    ```
    pip install stata_kernel --upgrade
    ```
    and check if your issue is fixed.

#### Debugging log

If possible, attach the text file located at

```
$HOME/.stata_kernel_cache/console_debug.log
```
where `$HOME` is your home directory. This will help us debug your problem quicker.

**NOTE: This file includes a history of your session. If you work with restricted data, do not include this file.**

#### Code Sample

Especially if you cannot attach the debugging log, please include a [minimal, complete, and verifiable example.](https://stackoverflow.com/help/mcve)

```stata
use "https://stats.idre.ucla.edu/stat/stata/notes/hsb2", clear
scatter read math, title("Reading score vs Math score")
scatter math science, title("Math score vs Science score")

```

#### Expected Output
![image](https://user-images.githubusercontent.com/43084101/117167938-4cfcd780-adfa-11eb-9ae9-e2e1196bed88.png)

#### unexpected output
Just display like this, 

![image](https://user-images.githubusercontent.com/43084101/117168011-600fa780-adfa-11eb-954c-eb792e950d84.png)

If you didn't attach the debugging log, please provide:

- Operating System win10
- Stata version 17.0
- Package version 1.12.2 (You can find this by running `pip show stata_kernel` in your terminal.)

**Comment by mcaceresb** [comment]
@ZHULOO Does it display if you add `graph display` after the commands are run?

**Comment by mcaceresb** [comment]
@simon-d-s Ah, interesting. That sounds straightforward if that's all it is. Try installing from [this branch](https://github.com/mcaceresb/stata_kernel/tree/dev-stata17-graph-fix). If it works then I'll make a PR.

**Comment by simon-d-s** [comment]
@mcaceresb unfortunatly, it's not all. it seems that under Stata 17, `capture noisily` suppresses the `(note: file foo.png not found)` issued in earlier versions of Stata. This seems to be relevant for the first line of `clean_log_eol()` in stata_session.py, if my reading of the code is correct (sorry, I'm a python beginner)

**Comment by kylebarron** [comment]
If anyone is on Stata 17 and would like to take a deeper look and submit a Pull Request, that might move things a bit faster.

**Comment by ZHULOO** [comment]
Thanks you guys for the discussion, when I run `scatter math science, title("Math score vs Science score")`, The Stata17 has generated the " .png" figure in the cached directories,But It just does not display the figure in the notebook.

**Comment by simon-d-s** [comment]
First: apologies, my above statement:
> @mcaceresb unfortunatly, it's not all. it seems that under Stata 17, `capture noisily` suppresses the `(note: file foo.png not found)` issued in earlier versions of Stata. This seems to be relevant for the first line of `clean_log_eol()` in stata_session.py, if my reading of the code is correct (sorry, I'm a python beginner)

... is wrong (it seems that I've created a mess fiddling around simultaneously with Stata 16 and 17...).

What is correct, however, is the following:

- The note Stata issues after `graph export path/foo.png, replace` if foo.png does not already exist reads `(note: file path/foo.png not found)` under Stata 16 but `(file path/foo.png not found)`  (without "note:") under Stata 17.
- The note Stata issues after successfully saving path/foo.png reads `(file path/foo.png written in PNG format)` under Stata 16 but `(file path/foo.png saved as PNG format`  (without parentheses)  under Stata 17.

Obviously this makes it difficult to define `g_exp` in `expect()` for both Stata 16 and 17. -> it may be necessary to add a config-setting for the Stata-version in use (or read it from the `c(version)` in Stata?).

For my own use, I adapted `g_expect` to `g_exp = r'^file {}'.format(self.cache_dir_str[:34])`, changed the regex in `clean_log_eol()`  to `r'^\((?:note: )?file {}/graph\d+\.({}) not found\)'...` and left the one in `expect_graph()` unchanged compared to #392, which fixes the issue.

**Comment by mcaceresb** [comment]
@simon-d-s Can you try it from [this branch](https://github.com/mcaceresb/stata_kernel/tree/dev-stata17-graph-fix)? I've made the `note: ` optional in the `regex`. It's easier than trying to change it based on the user's state version, and given the `not found` is still there I think it's probably good enough.

**Comment by simon-d-s** [comment]
@mcaceresb , sorry for not being clear enough. The main issues stems from `g_exp` on [line 302 of stata_session.py](https://github.com/kylebarron/stata_kernel/blob/ec3f51c2f4b2cf5469a53b7de06f9511ebd07ba4/stata_kernel/stata_session.py#L302)

The existing code `g_exp = r'\(file {}'.format(self.cache_dir_str[:34])` will capture the beginning of `(file path/foo.png not found)` issued by Stata 17, instead of the beginning of `file path/foo.png saved as PNG format`. => works for Stata 16, but not for Stata 17.

Conversely, if I use  `g_exp = r'(?<!\()file {}'.format(self.cache_dir_str[:34])` in order to make it work with Stata 17, it will not work with Stata 16.

So, the problem is that `r'\(file {}'.format(self.cache_dir_str[:34])'` exists in both Stata 16 and Stata 17, but they appear in different contexts.

**Comment by mcaceresb** [comment]
@simon-d-s Does it work if you set: `g_exp = r'\(?file {}'.format(self.cache_dir_str[:34])`?

**Comment by ZHULOO** [comment]
The notebook terminal display like this 
![notebook](https://user-images.githubusercontent.com/43084101/118355438-9be90080-b5a2-11eb-9d71-3f5301bff62f.png)

**Comment by simon-d-s** [comment]
@mcaceresb It will work, but it will capture both the `(file path/foo.png not found)` from Stata 17 and the `(file path/foo.png written in PNG format)` from Stata <17.

I've created a PR with a possible solution for disentangling the two. Not sure whether it's a very elegant way of doing it, but it seems to work.

@mcaceresb  could you cross check with Stata 16?

**Comment by binyamink** [comment]
Hi, I'm experiencing a similar issue. I work from Atom on Windows 10, Stata 14, kernel version 1.12.2. The graph is created in the cache folder but not displayed and the session gets stuck. I attach the debugging log. I tried to use the simple example from above.

[console_debug.log](https://github.com/kylebarron/stata_kernel/files/6680903/console_debug.log)

Thanks a lot!

**Comment by izumis007** [comment]
I am having the exact same problem. I used older versions of stata_kernel and Stata 17 without any problems at all. But, today I updated to the new version of stata_kernel,  and graph suddenly wounld't displayed and I got stuck...

**Comment by gaksaray** [comment]
@binyamink @izumis007 I had the same problem using the kernel with Stata 17 but this seems to be solved in https://github.com/kylebarron/stata_kernel/pull/394 by @simon-d-s (at least for Stata 17). So you can install the kernel as usual and just replace the stata_session.py file with [this version](https://github.com/kylebarron/stata_kernel/blob/97709b6c46c1a01c670283ebd05920270044187d/stata_kernel/stata_session.py) and it should work until we get a new version of the kernel. I actually just created [a fork that streamlines this process](https://github.com/gaksaray/stata_kernel) for myself so you can try that too.

**Comment by izumis007** [comment]
@gaksaray Thank you for your advice! I'll try it out next week and report back with the results.

**Comment by izumis007** [comment]
@gaksaray It fixed! Thank you.
pip install didn't work well so I just copied your version of  stata_session.py and replaced it with the older one.
