### ISSUE TITLE
Stata syntax highlighting

### ISSUE THREAD

**Issue by TiesdeKok** [kylebarron/stata_kernel#4]
It might be worth mentioning that in the mean time (since our last chat about it at the end of 2017) I have managed to get my (admittedly hacky) Stata syntax highlighting working again in the Jupyter Notebook. 

The codemirror file is here: https://github.com/TiesdeKok/ipystata/blob/49acff7e13716d7baa7cf43be1b6b7c6cef9fc0c/ipystata/stata.js

I linked it to the `%%stata` magic but I am sure you can also just apply to an entire kernel.

See these lines of code [(link)](https://github.com/TiesdeKok/ipystata/blob/49acff7e13716d7baa7cf43be1b6b7c6cef9fc0c/ipystata/ipystata_magic.py#L454-L464): 
```
if config.enable_syntax_highlight:
	# Enable the stata syntax highlighting:
	#js = "IPython.CodeCell.config_defaults.highlight_modes['magic_stata'] = {'reg':[/^%%stata/]};"
	js = """require(['notebook/js/codecell'], function(codecell) {
			  codecell.CodeCell.options_default.highlight_modes['magic_stata'] = {'reg':[/^%%stata/]} ;
			  Jupyter.notebook.events.one('kernel_ready.Kernel', function(){
			      Jupyter.notebook.get_cells().map(function(cell){
			          if (cell.cell_type == 'code'){ cell.auto_highlight(); } }) ;
			  });
			});"""
	display.display_javascript(js, raw=True)
```

**Comment by kylebarron** [comment]
Have you ever tried to use IPyStata in a non-Jupyter Notebook environment? Specifically Hydrogen, Jupyter console, or Jupyter QtConsole? Jupyter Notebook is the only one of the four that use CodeMirror for syntax highlighting (Jupyter console and Qtconsole use Pygments, and Hydrogen uses my Atom Stata syntax highlighting package). I'm not sure it's ideal for me to be serving up Javascript that those frontends won't be able to handle.

The best option would just be to add Stata syntax highlighting to the CodeMirror repository itself. Though then there would be a lag until the next release and when Jupyter Notebook uses that next release.

I can look into this a bit more in the future, but at the moment it isn't a high priority compared to making sure the package is stable.

**Comment by stevencollinscn** [comment]
I've used Stata for a while just realized that "in" doesn't get highlighted in Stata's syntax?

**Comment by kylebarron** [comment]
Highlighted where? Are you using Jupyter Notebook, Jupyter Console, or Atom? Each uses different syntax highlighters.

**Comment by stevencollinscn** [comment]
The syntax doesn't get highlighted in Jupyter Lab unless I export an HTML file. nteract doesn't highlight the syntax either. It seems only Atom does so far based on your stata-language package.

**Comment by kylebarron** [comment]
Jupyter notebook and I assume Jupyter lab and the nteract desktop app all use codemirror for syntax highlighting. Codemirror doesn't have Stata syntax highlighting yet, and I haven't taken the time to create a pr with one, though only slight modifications from the above file should be needed

**Comment by kylebarron** [comment]
@TiesdeKok Is it OK with you if I start with your Codemirror `stata.js` syntax highlighting file, modify it, and submit it as a pull request to the Codemirror repository?

**Comment by kylebarron** [comment]
@TiesdeKok In case you wanted to give some input, I'll be working on the Stata mode on [my fork](https://github.com/kylebarron/CodeMirror) of the CodeMirror repo.

**Comment by TiesdeKok** [comment]
Most definitely, thanks for picking that up! I will do my best to find some time to go through it at some point as well.

**Comment by kylebarron** [comment]
I ended up starting over from scratch. There are two ways to write a syntax highlighter for codemirror, a simple way that uses regular expressions and a complex way where you do all the low level parsing yourself. R uses the complex way, so thus your fork did as well. It was much easier to start from scratch.

**Comment by kylebarron** [comment]
@TiesdeKok In case you wanted to test it, (and have node.js installed) you can do

```
git clone https://github.com/kylebarron/codemirror
cd codemirror
npm install
```

Then open `./mode/stata/index.html` in your web browser.

**Comment by kylebarron** [comment]
I took an hour to look into it a little more... Since ipystata is a magic and not a kernel, you have to add that extra javascript in your code to register the syntax highlighting with the magic. In contrast, since stata_kernel is an actual kernel, I don't have to do give any extra javascript; if the highlighting file `stata.js` exists in the `notebook` package, then it will highlight Stata.

So even without a PR to codemirror, all I need to do is
```
from pkg_resources import resource_filename
path = resource_filename('notebook', 'static/components/codemirror/mode/stata/stata.js')
```

and then if `path` doesn't exist, copy the contents of `stata.js` there.
