### ISSUE TITLE
Text wrapping with long input/output using shell

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#41]
![image](https://user-images.githubusercontent.com/15164633/43853372-f28995b0-9b0d-11e8-9dfe-ec40dd24d749.png)

**Comment by kylebarron** [comment]
Pros-vs-cons of setting wider terminal size:

**Pros**
- Most screens are wider than 80 characters. But when the terminal is set to 80 chars, the output is never wider than 80 chars. For example:
![image](https://user-images.githubusercontent.com/15164633/43853583-908819da-9b0e-11e8-8dd9-475b0e54edf6.png)
    And this is on a vertical montor. Most people use horizontal monitors and might want to be able to view their results with less vertical space

**Cons**
- It's hard to know what a good width value is. 

Note that both input and output wraps like this:
![image](https://user-images.githubusercontent.com/15164633/43853718-f0709c96-9b0e-11e8-892b-b6c121af93ac.png)

**Comment by mcaceresb** [comment]
You could set the width to `c(linesize)`, whatever that might be.
