### ISSUE TITLE
%time/%timeit magic

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#51]
@mcaceresb You made a simple Stata benchmarking script didn't you?

**Comment by mcaceresb** [comment]
Yes, but is it possible to add a series of .ado programs on kernel startup? My intuition is that this would be easier to do from python directly. I'll look into it and add it to the PR once `dev` gets merged.

**Comment by kylebarron** [comment]
Well there's nothing stopping it from adding `.ado` programs, but it could be just as easy from Python, as long as there's no variation in the time it takes to send/receive information from Python to Stata.

**Comment by mcaceresb** [comment]
K. Will try both and see if the variance is significant.

**Comment by kylebarron** [comment]
Closing this for now. We can come back to %timeit in the future
