### ISSUE TITLE
Support keyboard interrupts

### ISSUE THREAD

**Issue by mcaceresb** [kylebarron/stata_kernel#53]
**Is your feature request related to a problem? Please describe.**
Keyboard interrupts (Ctrl+C) should be supported whenever possible. In the console version of Stata this is akin to hitting the "break" button. This is generally useful but would also help with a common mistake (that at least I make): Sometimes I put a command that would have Stata printing stuff to the console for several minutes, and Ctrl+C is very helpful to break that.

**Describe the solution you'd like**
The following works for me in `run_shell` but I haven't tested it too thoroughly.
```python
for line in lines:
    try:
        self.child.sendline(line)
        self.child.expect('(?<=(\r\n)|(\x1b=))\r\n\. ', timeout=20)
    except KeyboardInterrupt:
        self.child.send('\003')
        self.child.expect('(?<=(\r\n)|(\x1b=))\r\n\. ', timeout=20)
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kylebarron** [comment]
Yes I agree. #23

**Comment by mcaceresb** [comment]
Ah, I looked for a related issue and didn't find it. The issue I ran into doing it directly from `do_execute` is that the code fell out of sync with the output.

**Comment by mcaceresb** [comment]
At any rate, this is a duplicate of #23.
