### ISSUE TITLE
Automagically detect Stata version (and plot extension)?

### ISSUE THREAD

**Issue by mcaceresb** [kylebarron/stata_kernel#68]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
`language_version` is set to 15.1. Should it be set to "\`c(stata_version)'"?

**Describe alternatives you've considered**
N/A

**Additional context**
Depending on the Stata version, note that SVG images might not be supported/decide the plot extension?

I think you can do:

```
    _language_version = None

    @property
    def language_version(self):
        if self._language_version:
            return self._language_version
        else:
            cm = CodeManager("disp `c(stata_version)'", False)
            return self.stata.do(cm.get_chunks(), self.magics)[-1]
```

**Comment by mcaceresb** [comment]
This might be useful to change the default plot from `.svg` to `.tif` if the stata version is < 15.

**Comment by mcaceresb** [comment]
`png` doesn't work for me.

**Comment by mcaceresb** [comment]
Interesting. Apparently 14 _can_ do svg.

**Comment by kylebarron** [comment]
I think non-Linux 13/14 can do png... I think Linux 14/15 can do svg, and I think Mac 14 can do svg, but maybe Windows 14 can't do svg:
https://github.com/kylebarron/stata_kernel/issues/21

**Comment by kylebarron** [comment]
`self.language_version` is now set correctly.

https://github.com/kylebarron/stata_kernel/commit/4f085d4a61e9556a7b59949f2be5f43b02b5e90d

**Comment by kylebarron** [comment]
Fixed again with https://github.com/kylebarron/stata_kernel/commit/7b5ebb2a055ec9847e590bb64d3f6c36d9338f20
