### ISSUE TITLE
Set more to x number of pages?

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#77]
Currently on starting, the kernel does `set more off`. If someone loads a 1 million row dataset and types `list`, 1 million rows of the data will be printed on the screen or until the user `KeyboardInterrupt`s. This is probably undesirable, as some users won't know to `Ctrl-C`, and it's slightly different on Hydrogen and Jupyter Notebook.

So probably set `set more 10` or something at the beginning, and then also `expect` for `\r\n--more--`. Then if you hit that, automatically press `q` and tell user that output was shortened by `more`.

Note that `set more 1` doesn't work for shell commands. `!yes` runs forever.

**Comment by mcaceresb** [comment]
I don't think `set more #` does what you think it does. The behavior of `set more` seems buggy, tbh. Most inputs will yell `on or off required` BUT

```
. set more 30001
more must be between 0 and 30000
r(198);
```

The plot thickens! My guess is that `0` was meant to set more on and `1` was meant to set it off.
```stata
set more on
set pagesize 2
set more 1
disp "`c(more)'"
set more 0
disp "`c(more)'"
```

Shows `more` is `off` after `1` and `on` after `0` (and pauses at the end). However, 
```
set more off
set pagesize 2
set more 99
disp "`c(more)'"
```

Shows more is off but pauses! Anyway, you want to set `pagesize`, not `more` to control the number of lines.

**Comment by kylebarron** [comment]
Thanks

**Comment by mcaceresb** [comment]
My head just exploded: Apparently if you `set more #` where `# > 1` Stata enters more, pauses for `#` seconds, scrolls `more` by `c(pagesize)`, and repeats this behavior until it has scrolled all the lines captured by `more`. See [this thread](https://www.statalist.org/forums/forum/general-stata-discussion/general/1458526-bug-in-set-more).

Since more is on, off, or pauses for at least 2s, I think the capturing code will still work, however.

**Comment by kylebarron** [comment]
I guess this doesn't need to be exposed in `%set` since doing `set pagesize 50` will work just as well.

**Comment by mcaceresb** [comment]
`more` crashes the kernel for me btw

**Comment by kylebarron** [comment]
This is because it also removes the `` ` `` on the next line. If I change the md5 expect back to `` `md5'`` instead of the current ``. `md5'``, this should work. I'm not sure if the difference actually helped me.

**Comment by kylebarron** [comment]
![image](https://user-images.githubusercontent.com/15164633/44378246-75b7d400-a4ce-11e8-9b50-af4f05088bf9.png)

**Comment by kylebarron** [comment]
Pagesize is already set to 100 by default.
