### ISSUE TITLE
Cannot access local macros in Jupyter

### ISSUE THREAD

**Issue by maraab23** [kylebarron/stata_kernel#81]
#### Code Sample

```stata
local test "tree house"
display "`test'"

* result:	`test'
* instead of:	tree house

```
#### Problem description

First of all, thanks for your great work. I intend to use this for teaching. However, I encountered the problem that I cannot access local macros in my Jupyter notebook. If I use a global instead of a local macro the ```display``` command still does not work as expected, although in both cases the macros are correctly generated (as shown by ```%locals``` or ```%globals```). Although the issue seems to be identical for both local and global macros there is a important difference:

The local macro (``` `xvars' ```) simply seems to be ignored:
```stata
sysuse auto
local xvars "mpg rep78 headroom"
regress price `xvars'
```
```
(1978 Automobile Data)

      Source |       SS           df       MS      Number of obs   =        74
-------------+----------------------------------   F(0, 73)        =      0.00
       Model |           0         0           .   Prob > F        =         .
    Residual |   635065396        73  8699525.97   R-squared       =    0.0000
-------------+----------------------------------   Adj R-squared   =    0.0000
       Total |   635065396        73  8699525.97   Root MSE        =    2949.5

------------------------------------------------------------------------------
       price |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
       _cons |   6165.257   342.8719    17.98   0.000     5481.914      6848.6
------------------------------------------------------------------------------
```

... whereas the global macro (``` $xvars ```) works as expected:

```stata
sysuse auto
global xvars "mpg rep78 headroom"
regress price $xvars
```
```
(1978 Automobile Data)

      Source |       SS           df       MS      Number of obs   =        69
-------------+----------------------------------   F(3, 65)        =      7.51
       Model |   148497605         3  49499201.8   Prob > F        =    0.0002
    Residual |   428299354        65  6589220.82   R-squared       =    0.2575
-------------+----------------------------------   Adj R-squared   =    0.2232
       Total |   576796959        68  8482308.22   Root MSE        =    2566.9

------------------------------------------------------------------------------
       price |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
         mpg |  -289.3462   62.53921    -4.63   0.000    -414.2456   -164.4467
       rep78 |   670.8971   343.5213     1.95   0.055    -15.16242    1356.957
    headroom |  -300.0293   398.0516    -0.75   0.454    -1094.993    494.9346
       _cons |   10921.33   2153.003     5.07   0.000     6621.487    15221.17
------------------------------------------------------------------------------
```

#### Package Version

Version: 1.3.1

**Comment by kylebarron** [comment]
Thanks for the detailed report. Which operating system are you using?

**Comment by maraab23** [comment]
Windows 10 (& Stata SE 15.1)

**Comment by kylebarron** [comment]
This is actually a bug in Stata itself, not in my program, though there seems to be a workaround.

There are two ways to send commands to Stata on Windows using Stata Automation. I've been using one of them, which seems nicer because tells me if the command stopped due to an error. It turns out that that command is incapable of using local macros.

![image](https://user-images.githubusercontent.com/15164633/44215045-8b7c7080-a13f-11e8-9a79-159e98ba8d1a.png)

I should be able to push out a quick temporary fix for this, by using the latter method of sending commands to Stata.

I'll also send a bug report to StataCorp, but they don't really put much investment into this part of Stata.

**Comment by kylebarron** [comment]
Sorry, the fix isn't quite as quick as I'd hoped. It should be fixed in a couple days with the new release.

**Comment by maraab23** [comment]
Thanks for looking into this. I am looking forward to the new release.

**Comment by kylebarron** [comment]
> I spoke with out developers, and their response was:
>
> DoCommand can not expand a local macro- it is using a very different
command execution mechanisim than DoCommandAsync, which is more
like typing a command in the Command Window and then pressing the return
keys.

That's Stata for you. The new branch is tentatively working, but there's several things I need to clean up on that first before I can release it.

**Comment by kylebarron** [comment]
This should be fixed on the master branch. I don't have access to a Windows computer until tomorrow morning. I expect it should work fine, but want to test it a little before I push a new release to `pip`. Until then, you can do `pip install git+https://github.com/kylebarron/stata_kernel --upgrade` to test out the master branch. 

Reopen if you still have issues.
