### ISSUE TITLE
Move all configuration into a single file

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#82]
@mcaceresb I'm trying to put all the configuration into it's own module. And have a method in there that has `.get()` and `.set(permanently=False)`. If I instantiate the class in `kernel.py`, and pass the instantiated class object to each other module, will a `.set(permanently=False)` be updated everywhere? I.e. is the class the same object in all files?

I couldn't think of a super quick way to test this.

**Comment by kylebarron** [comment]
Do you not have to pass `object` as an argument to the class name?

![image](https://user-images.githubusercontent.com/15164633/44240649-3e26f000-a18d-11e8-8c25-8edb16c92d6a.png)

**Comment by mcaceresb** [comment]
`object` AFAIK is an optional argument meant to be a `class` itself. The declared class inherits the methods  from `object`. You can specify multiple objects.

**Comment by kylebarron** [comment]
Wow, I didn't know that. I've always written the word `object`.

**Comment by mcaceresb** [comment]
`object` is the most base type; it might default to it anyway.
