### ISSUE TITLE
Support rich output types

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#86]
You can have [many types of output](https://nbviewer.jupyter.org/github/ipython/ipython/blob/master/examples/IPython%20Kernel/Rich%20Output.ipynb) embedded in a Jupyter Notebook.

- [LaTeX](https://nbviewer.jupyter.org/github/ipython/ipython/blob/master/examples/IPython%20Kernel/Rich%20Output.ipynb#LaTeX); sadly it seems as if MathJax doesn't support tabular, so this might actually not be too useful.
- [HTML](https://nbviewer.jupyter.org/github/ipython/ipython/blob/master/examples/IPython%20Kernel/Rich%20Output.ipynb#HTML); There probably aren't too many Stata commands that export HTML...

**Comment by mcaceresb** [comment]
However, you could display HTML help.

**Comment by kylebarron** [comment]
This is true. I'm working on a simple `browse` data explorer. As an example:
![image](https://user-images.githubusercontent.com/15164633/44316094-bbee3400-a3f7-11e8-8c0c-fc821291801a.png)

**Comment by mcaceresb** [comment]
I've had problems getting HTML help to display, but you seem to have it figured out.

**Comment by kylebarron** [comment]
5 lines to create that:

```py
import pandas as pd
df = pd.read_csv('/Users/Kyle/github/stata/stata-kernel/test.csv')
html = df.to_html(na_rep = '.', notebook=True)
content = {'data': {'text/html': html}, 'metadata': {},}
self.send_response(self.iopub_socket, 'display_data', content)
```

I can already hear your groan at adding Pandas as a dependency... haha

**Comment by mcaceresb** [comment]
I def tried that and it failed. Will give it another go.

**Comment by kylebarron** [comment]
I'm gonna create the basic `browse` functionality, but I might ask for your help in adding argumentparser options.

**Comment by kylebarron** [comment]
Also HTML help... how do you suggest doing that? `wget https://www.stata.com/help.cgi?{command}`?

**Comment by mcaceresb** [comment]
I tried something like

```

        from urllib import request
        cmd  = "help"
        html = request.urlopen(" https://www.stata.com/help.cgi?" + cmd).read()
        resp = {'data': {'text/html': html.decode("utf-8")}, 'metadata': {},}
        self.send_response(self.iopub_socket, 'display_data', resp)
```

But failed.

**Comment by kylebarron** [comment]
![image](https://user-images.githubusercontent.com/15164633/44316712-1a68e180-a3fb-11e8-988e-b855904b9850.png)

**Comment by kylebarron** [comment]
It's actually quite fast for me.

**Comment by mcaceresb** [comment]
To get your head spinning, think about value labels, display formats, etc.

**Comment by kylebarron** [comment]
Yes but I think `export delimited` takes care of most of that...

I'm using `datafmt` "use the variables' display format upon export" and not using `nolabel` "output numeric values (not labels) of labeled variables".

**Comment by kylebarron** [comment]
See #88

**Comment by kylebarron** [comment]
I tested out displaying HTML help, but it looks kinda weird, at least in Atom, because it grabs some of the styling from the Stata page. Esp with the dark theme, the border of the html was white, and the inside was dark.

**Comment by mcaceresb** [comment]
I can't get it to display at all, so you're way ahead!

**Comment by kylebarron** [comment]
I'm surprised. I did basically the same thing but with `requests`

**Comment by mcaceresb** [comment]
It turns out that the problem is just that qtconsole does not support html ):

It works just fine on a notebook.

**Comment by kylebarron** [comment]
That's not _too_ surprising. It's impressive it supports svg/png.
