### ISSUE TITLE
Issues with log cleaning

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#90]
Not sure whether I should 
1) Try to fix cleaning code
2) Try to remove any newlines from input code that aren't inside strings.

@mcaceresb 

#### Code Sample

```stata
program main
    /* """Main program

    This is the only program called directly. It runs the rest of the file in
    the correct order.
    """ */

    syntax, [CAPture NOIsily email]

    * Set up
    * ------

    local  progname "filename"
    local  start_time "$S_TIME $S_DATE"
    di "Start: `start_time'"

    di "hi"

end
```
![image](https://user-images.githubusercontent.com/15164633/44350898-80db1780-a46e-11e8-8ac5-b8a4d2f31314.png)

**Comment by mcaceresb** [comment]
My take is that if a given command prints nothing, all newlines should be stripped. If it does print stuff it's fine to leave them in, regardless of where the newline is from.

**Comment by kylebarron** [comment]
Well yes but
1. It's impossible to know when you hit the first `\n` whether the command prints nothing, because it could print stuff after. I suppose I could refrain from sending back anything until I hit the first non whitespace line. Then once I hit that send back that line's text in addition to the previous newlines that I had withheld.
2. As you can tell from the screenshot, my lexer includes preceding newlines with a command. So the lexer changes `\s\s\s\s\* Set up\n` to `\s\s\s\s\n`. But that's still sent with `local progname "filename"`. So I think it would make sense to strip those repetitive newlines from the input. Then it would send just `local progname "filename"` or possibly `    local progname filename` instead of `\n\t\n\t\n\t\n\tlocal progname filename`.
 sometimes there are extra
