### ISSUE TITLE
Local macro completion not working

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#92]
@mcaceresb I'm wondering if the new PR yesterday messed this up. Can you try from master at your leisure?

(The suggestion in Atom is from the language-stata package, there should be another one with a Hydrogen icon with the same suggestion).

![image](https://user-images.githubusercontent.com/15164633/44353003-cb12c780-a473-11e8-9b5e-146d0f6c4aa2.png)
![image](https://user-images.githubusercontent.com/15164633/44353013-d108a880-a473-11e8-8ec0-dd3383887613.png)

**Comment by kylebarron** [comment]
This appears to be because it catches the MD5 too early. I'm not sure whether I should try to always match ``. `md5'`` instead of just `` `md5'``.
![image](https://user-images.githubusercontent.com/15164633/44354041-c3a0ed80-a476-11e8-9294-d1227bdcb5a8.png)

**Comment by kylebarron** [comment]
I changed the md5 matching to `. md5` but this is still an issue.

**Comment by mcaceresb** [comment]
I've fixed this. One sec I'm gonna update the PR soon.
