### ISSUE TITLE
Incorrect parsing of _StataKernelCompletions

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#93]
I'm removing an extra letter of every line continuation

autocompletion:
![image](https://user-images.githubusercontent.com/15164633/44354374-b33d4280-a477-11e8-9af3-8fbf3ea271db.png)

output:
![image](https://user-images.githubusercontent.com/15164633/44354353-a4569000-a477-11e8-8c36-fb844af38e72.png)

**Comment by kylebarron** [comment]
The quick fix is to set linesize higher within the completions script, but since linesize has a max of 255, this is just a bandaid

**Comment by mcaceresb** [comment]
I've also fixed this.

**Comment by kylebarron** [comment]
Too late haha.. It's probably best for it to be fixed inside `expect()` anyways, since there are other internal functions that call `stata.do()`.
